import {
  Type, AlignLeft, Image, Video, Columns, Square, Minus, MoveVertical,
  Navigation, Menu, Link2, MapPin,
  FormInput, MousePointer, Mail, ToggleLeft, ListChecks,
  Table, List, LayoutGrid, Hash,
  ShoppingCart, CreditCard, Tag, Megaphone,
  Users, MessageSquare, Star, Heart,
  BarChart3, LineChart, PieChart, TrendingUp,
  Package, Wallet, UserCheck, ClipboardList,
  Heading1, Heading2, Quote, Code, FileText,
  Play, GalleryHorizontal, ImageIcon,
  Search, ChevronDown, Calendar, Clock,
  Globe, Phone, Send, Shield,
  Truck, Building2, Ticket, Target, Award,
  Utensils, Receipt, Store, Layers, Plug,
  QrCode, Barcode, Warehouse, BookOpen, Briefcase,
} from 'lucide-react';
import { WidgetDefinition, WidgetCategory } from '../types';

export const widgetRegistry: WidgetDefinition[] = [
  // ===== LAYOUT =====
  {
    type: 'container',
    name: 'Kontainer',
    icon: Square,
    category: 'layout',
    description: 'Kontainer fleksibel untuk mengelompokkan elemen',
    defaultSize: { w: 12, h: 4 },
    minSize: { w: 2, h: 2 },
    properties: [
      { key: 'backgroundColor', label: 'Warna Latar', type: 'color', defaultValue: '#ffffff', group: 'Style' },
      { key: 'borderRadius', label: 'Radius Border', type: 'slider', defaultValue: 8, min: 0, max: 32, group: 'Style' },
      { key: 'borderWidth', label: 'Lebar Border', type: 'slider', defaultValue: 0, min: 0, max: 4, group: 'Style' },
      { key: 'borderColor', label: 'Warna Border', type: 'color', defaultValue: '#e5e7eb', group: 'Style' },
      { key: 'padding', label: 'Padding', type: 'slider', defaultValue: 16, min: 0, max: 64, group: 'Style' },
      { key: 'shadow', label: 'Bayangan', type: 'select', defaultValue: 'none', options: [
        { label: 'Tanpa', value: 'none' }, { label: 'Kecil', value: 'sm' },
        { label: 'Sedang', value: 'md' }, { label: 'Besar', value: 'lg' }, { label: 'Ekstra', value: 'xl' },
      ], group: 'Style' },
    ],
  },
  {
    type: 'columns',
    name: 'Kolom',
    icon: Columns,
    category: 'layout',
    description: 'Layout kolom fleksibel (2-4 kolom)',
    defaultSize: { w: 12, h: 4 },
    minSize: { w: 4, h: 2 },
    properties: [
      { key: 'columnCount', label: 'Jumlah Kolom', type: 'select', defaultValue: '2', options: [
        { label: '2 Kolom', value: '2' }, { label: '3 Kolom', value: '3' }, { label: '4 Kolom', value: '4' },
      ], group: 'Layout' },
      { key: 'gap', label: 'Jarak Antar', type: 'slider', defaultValue: 16, min: 0, max: 48, group: 'Layout' },
      { key: 'backgroundColor', label: 'Warna Latar', type: 'color', defaultValue: 'transparent', group: 'Style' },
    ],
  },
  {
    type: 'divider',
    name: 'Pembatas',
    icon: Minus,
    category: 'layout',
    description: 'Garis pembatas horizontal',
    defaultSize: { w: 12, h: 1 },
    minSize: { w: 2, h: 1 },
    maxSize: { w: 12, h: 1 },
    properties: [
      { key: 'color', label: 'Warna', type: 'color', defaultValue: '#e5e7eb', group: 'Style' },
      { key: 'thickness', label: 'Ketebalan', type: 'slider', defaultValue: 1, min: 1, max: 8, group: 'Style' },
      { key: 'style', label: 'Gaya', type: 'select', defaultValue: 'solid', options: [
        { label: 'Solid', value: 'solid' }, { label: 'Dashed', value: 'dashed' }, { label: 'Dotted', value: 'dotted' },
      ], group: 'Style' },
      { key: 'marginY', label: 'Margin Vertikal', type: 'slider', defaultValue: 16, min: 0, max: 64, group: 'Style' },
    ],
  },
  {
    type: 'spacer',
    name: 'Spasi',
    icon: MoveVertical,
    category: 'layout',
    description: 'Ruang kosong vertikal',
    defaultSize: { w: 12, h: 2 },
    minSize: { w: 1, h: 1 },
    properties: [
      { key: 'height', label: 'Tinggi (px)', type: 'slider', defaultValue: 40, min: 8, max: 200, group: 'Layout' },
    ],
  },

  // ===== TEXT =====
  {
    type: 'heading',
    name: 'Judul',
    icon: Heading1,
    category: 'text',
    description: 'Judul H1 - H6',
    defaultSize: { w: 12, h: 2 },
    minSize: { w: 3, h: 1 },
    properties: [
      { key: 'text', label: 'Teks', type: 'text', defaultValue: 'Judul Halaman', group: 'Konten' },
      { key: 'level', label: 'Level', type: 'select', defaultValue: 'h1', options: [
        { label: 'H1', value: 'h1' }, { label: 'H2', value: 'h2' }, { label: 'H3', value: 'h3' },
        { label: 'H4', value: 'h4' }, { label: 'H5', value: 'h5' }, { label: 'H6', value: 'h6' },
      ], group: 'Konten' },
      { key: 'color', label: 'Warna', type: 'color', defaultValue: '#111827', group: 'Style' },
      { key: 'alignment', label: 'Perataan', type: 'alignment', defaultValue: 'left', group: 'Style' },
      { key: 'fontWeight', label: 'Tebal Font', type: 'select', defaultValue: 'bold', options: [
        { label: 'Normal', value: 'normal' }, { label: 'Medium', value: '500' },
        { label: 'Semi Bold', value: '600' }, { label: 'Bold', value: 'bold' }, { label: 'Extra Bold', value: '800' },
      ], group: 'Style' },
    ],
  },
  {
    type: 'paragraph',
    name: 'Paragraf',
    icon: AlignLeft,
    category: 'text',
    description: 'Blok teks paragraf',
    defaultSize: { w: 12, h: 3 },
    minSize: { w: 3, h: 2 },
    properties: [
      { key: 'text', label: 'Teks', type: 'textarea', defaultValue: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', group: 'Konten' },
      { key: 'fontSize', label: 'Ukuran Font', type: 'slider', defaultValue: 16, min: 12, max: 24, group: 'Style' },
      { key: 'color', label: 'Warna', type: 'color', defaultValue: '#4b5563', group: 'Style' },
      { key: 'lineHeight', label: 'Spasi Baris', type: 'slider', defaultValue: 1.6, min: 1, max: 3, step: 0.1, group: 'Style' },
      { key: 'alignment', label: 'Perataan', type: 'alignment', defaultValue: 'left', group: 'Style' },
    ],
  },
  {
    type: 'richtext',
    name: 'Teks Kaya',
    icon: FileText,
    category: 'text',
    description: 'Blok teks dengan format kaya',
    defaultSize: { w: 12, h: 4 },
    minSize: { w: 4, h: 2 },
    properties: [
      { key: 'content', label: 'Konten HTML', type: 'textarea', defaultValue: '<p>Tulis konten Anda di sini dengan <strong>format kaya</strong> dan <em>gaya teks</em>.</p>', group: 'Konten' },
      { key: 'padding', label: 'Padding', type: 'slider', defaultValue: 16, min: 0, max: 48, group: 'Style' },
    ],
  },
  {
    type: 'quote',
    name: 'Kutipan',
    icon: Quote,
    category: 'text',
    description: 'Blok kutipan dengan gaya',
    defaultSize: { w: 8, h: 3 },
    minSize: { w: 4, h: 2 },
    properties: [
      { key: 'text', label: 'Kutipan', type: 'textarea', defaultValue: 'Kesuksesan adalah hasil dari persiapan, kerja keras, dan belajar dari kegagalan.', group: 'Konten' },
      { key: 'author', label: 'Penulis', type: 'text', defaultValue: '— Colin Powell', group: 'Konten' },
      { key: 'accentColor', label: 'Warna Aksen', type: 'color', defaultValue: '#3b82f6', group: 'Style' },
      { key: 'backgroundColor', label: 'Warna Latar', type: 'color', defaultValue: '#f8fafc', group: 'Style' },
    ],
  },
  {
    type: 'code',
    name: 'Kode',
    icon: Code,
    category: 'text',
    description: 'Blok kode dengan syntax highlighting',
    defaultSize: { w: 12, h: 4 },
    minSize: { w: 4, h: 2 },
    properties: [
      { key: 'code', label: 'Kode', type: 'textarea', defaultValue: 'const greeting = "Hello World";\nconsole.log(greeting);', group: 'Konten' },
      { key: 'language', label: 'Bahasa', type: 'select', defaultValue: 'javascript', options: [
        { label: 'JavaScript', value: 'javascript' }, { label: 'TypeScript', value: 'typescript' },
        { label: 'HTML', value: 'html' }, { label: 'CSS', value: 'css' }, { label: 'Python', value: 'python' },
      ], group: 'Konten' },
      { key: 'theme', label: 'Tema', type: 'select', defaultValue: 'dark', options: [
        { label: 'Gelap', value: 'dark' }, { label: 'Terang', value: 'light' },
      ], group: 'Style' },
    ],
  },

  // ===== MEDIA =====
  {
    type: 'image',
    name: 'Gambar',
    icon: ImageIcon,
    category: 'media',
    description: 'Gambar dengan opsi gaya',
    defaultSize: { w: 6, h: 5 },
    minSize: { w: 2, h: 2 },
    properties: [
      { key: 'src', label: 'URL Gambar', type: 'text', defaultValue: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600', group: 'Konten' },
      { key: 'alt', label: 'Teks Alt', type: 'text', defaultValue: 'Deskripsi gambar', group: 'Konten' },
      { key: 'objectFit', label: 'Object Fit', type: 'select', defaultValue: 'cover', options: [
        { label: 'Cover', value: 'cover' }, { label: 'Contain', value: 'contain' }, { label: 'Fill', value: 'fill' },
      ], group: 'Style' },
      { key: 'borderRadius', label: 'Radius Border', type: 'slider', defaultValue: 8, min: 0, max: 50, group: 'Style' },
      { key: 'shadow', label: 'Bayangan', type: 'select', defaultValue: 'none', options: [
        { label: 'Tanpa', value: 'none' }, { label: 'Kecil', value: 'sm' }, { label: 'Sedang', value: 'md' }, { label: 'Besar', value: 'lg' },
      ], group: 'Style' },
    ],
  },
  {
    type: 'video',
    name: 'Video',
    icon: Play,
    category: 'media',
    description: 'Embed video YouTube/Vimeo',
    defaultSize: { w: 8, h: 6 },
    minSize: { w: 4, h: 3 },
    properties: [
      { key: 'url', label: 'URL Video', type: 'text', defaultValue: 'https://www.youtube.com/embed/dQw4w9WgXcQ', group: 'Konten' },
      { key: 'autoplay', label: 'Otomatis Putar', type: 'boolean', defaultValue: false, group: 'Pengaturan' },
      { key: 'borderRadius', label: 'Radius Border', type: 'slider', defaultValue: 8, min: 0, max: 24, group: 'Style' },
    ],
  },
  {
    type: 'gallery',
    name: 'Galeri',
    icon: GalleryHorizontal,
    category: 'media',
    description: 'Galeri gambar grid',
    defaultSize: { w: 12, h: 6 },
    minSize: { w: 6, h: 4 },
    properties: [
      { key: 'images', label: 'URL Gambar (pisah baris baru)', type: 'textarea', defaultValue: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=300\nhttps://images.unsplash.com/photo-1614850715649-1d0106293bd1?w=300\nhttps://images.unsplash.com/photo-1557672172-298e090bd0f1?w=300\nhttps://images.unsplash.com/photo-1579546929518-9e396f3cc809?w=300', group: 'Konten' },
      { key: 'columns', label: 'Kolom', type: 'select', defaultValue: '4', options: [
        { label: '2', value: '2' }, { label: '3', value: '3' }, { label: '4', value: '4' },
      ], group: 'Layout' },
      { key: 'gap', label: 'Jarak', type: 'slider', defaultValue: 8, min: 0, max: 24, group: 'Layout' },
      { key: 'borderRadius', label: 'Radius Border', type: 'slider', defaultValue: 8, min: 0, max: 24, group: 'Style' },
    ],
  },
  {
    type: 'icon',
    name: 'Ikon',
    icon: Star,
    category: 'media',
    description: 'Ikon dekoratif dengan ukuran dan warna',
    defaultSize: { w: 2, h: 2 },
    minSize: { w: 1, h: 1 },
    properties: [
      { key: 'iconName', label: 'Nama Ikon', type: 'select', defaultValue: 'star', options: [
        { label: 'Bintang', value: 'star' }, { label: 'Hati', value: 'heart' }, { label: 'Centang', value: 'check' },
        { label: 'Globe', value: 'globe' }, { label: 'Telepon', value: 'phone' }, { label: 'Email', value: 'mail' },
        { label: 'Lokasi', value: 'map-pin' }, { label: 'Jam', value: 'clock' }, { label: 'Perisai', value: 'shield' },
        { label: 'Zap', value: 'zap' }, { label: 'Target', value: 'target' }, { label: 'Award', value: 'award' },
      ], group: 'Konten' },
      { key: 'size', label: 'Ukuran', type: 'slider', defaultValue: 48, min: 16, max: 128, group: 'Style' },
      { key: 'color', label: 'Warna', type: 'color', defaultValue: '#3b82f6', group: 'Style' },
    ],
  },

  // ===== NAVIGATION =====
  {
    type: 'navbar',
    name: 'Navbar',
    icon: Navigation,
    category: 'navigation',
    description: 'Bilah navigasi atas',
    defaultSize: { w: 12, h: 2 },
    minSize: { w: 8, h: 2 },
    maxSize: { w: 12, h: 3 },
    properties: [
      { key: 'brandName', label: 'Nama Brand', type: 'text', defaultValue: 'Brand Saya', group: 'Konten' },
      { key: 'links', label: 'Link (pisah koma)', type: 'text', defaultValue: 'Beranda,Tentang,Layanan,Kontak', group: 'Konten' },
      { key: 'backgroundColor', label: 'Warna Latar', type: 'color', defaultValue: '#ffffff', group: 'Style' },
      { key: 'textColor', label: 'Warna Teks', type: 'color', defaultValue: '#111827', group: 'Style' },
      { key: 'sticky', label: 'Tetap di Atas', type: 'boolean', defaultValue: false, group: 'Pengaturan' },
    ],
  },
  {
    type: 'breadcrumb',
    name: 'Breadcrumb',
    icon: ChevronDown,
    category: 'navigation',
    description: 'Navigasi breadcrumb',
    defaultSize: { w: 12, h: 1 },
    minSize: { w: 4, h: 1 },
    properties: [
      { key: 'items', label: 'Item (pisah koma)', type: 'text', defaultValue: 'Beranda,Produk,Detail', group: 'Konten' },
      { key: 'separator', label: 'Pemisah', type: 'select', defaultValue: '/', options: [
        { label: '/', value: '/' }, { label: '>', value: '>' }, { label: '»', value: '»' },
      ], group: 'Style' },
    ],
  },
  {
    type: 'footer',
    name: 'Footer',
    icon: Menu,
    category: 'navigation',
    description: 'Footer website',
    defaultSize: { w: 12, h: 4 },
    minSize: { w: 8, h: 3 },
    properties: [
      { key: 'companyName', label: 'Nama Perusahaan', type: 'text', defaultValue: 'PT Bedagang Indonesia', group: 'Konten' },
      { key: 'description', label: 'Deskripsi', type: 'text', defaultValue: 'Platform ERP terpadu untuk bisnis Anda', group: 'Konten' },
      { key: 'links', label: 'Link (pisah koma)', type: 'text', defaultValue: 'Tentang,Layanan,Blog,Kontak', group: 'Konten' },
      { key: 'backgroundColor', label: 'Warna Latar', type: 'color', defaultValue: '#1f2937', group: 'Style' },
      { key: 'textColor', label: 'Warna Teks', type: 'color', defaultValue: '#f9fafb', group: 'Style' },
      { key: 'copyright', label: 'Hak Cipta', type: 'text', defaultValue: '© 2025 Bedagang. Hak cipta dilindungi.', group: 'Konten' },
    ],
  },

  // ===== FORMS =====
  {
    type: 'button',
    name: 'Tombol',
    icon: MousePointer,
    category: 'forms',
    description: 'Tombol aksi dengan gaya kustom',
    defaultSize: { w: 3, h: 2 },
    minSize: { w: 2, h: 1 },
    properties: [
      { key: 'text', label: 'Teks', type: 'text', defaultValue: 'Klik Saya', group: 'Konten' },
      { key: 'url', label: 'URL Tujuan', type: 'text', defaultValue: '#', group: 'Konten' },
      { key: 'variant', label: 'Varian', type: 'select', defaultValue: 'primary', options: [
        { label: 'Primary', value: 'primary' }, { label: 'Secondary', value: 'secondary' },
        { label: 'Outline', value: 'outline' }, { label: 'Ghost', value: 'ghost' },
      ], group: 'Style' },
      { key: 'size', label: 'Ukuran', type: 'select', defaultValue: 'md', options: [
        { label: 'Kecil', value: 'sm' }, { label: 'Sedang', value: 'md' }, { label: 'Besar', value: 'lg' }, { label: 'Ekstra', value: 'xl' },
      ], group: 'Style' },
      { key: 'fullWidth', label: 'Lebar Penuh', type: 'boolean', defaultValue: false, group: 'Style' },
      { key: 'borderRadius', label: 'Radius Border', type: 'slider', defaultValue: 8, min: 0, max: 24, group: 'Style' },
      { key: 'backgroundColor', label: 'Warna', type: 'color', defaultValue: '#3b82f6', group: 'Style' },
    ],
  },
  {
    type: 'input',
    name: 'Input',
    icon: FormInput,
    category: 'forms',
    description: 'Field input teks',
    defaultSize: { w: 6, h: 2 },
    minSize: { w: 3, h: 1 },
    properties: [
      { key: 'label', label: 'Label', type: 'text', defaultValue: 'Nama Lengkap', group: 'Konten' },
      { key: 'placeholder', label: 'Placeholder', type: 'text', defaultValue: 'Masukkan nama...', group: 'Konten' },
      { key: 'type', label: 'Tipe', type: 'select', defaultValue: 'text', options: [
        { label: 'Teks', value: 'text' }, { label: 'Email', value: 'email' },
        { label: 'Password', value: 'password' }, { label: 'Nomor', value: 'number' },
      ], group: 'Pengaturan' },
      { key: 'required', label: 'Wajib Diisi', type: 'boolean', defaultValue: false, group: 'Pengaturan' },
    ],
  },
  {
    type: 'contactForm',
    name: 'Form Kontak',
    icon: Mail,
    category: 'forms',
    description: 'Formulir kontak lengkap',
    defaultSize: { w: 8, h: 8 },
    minSize: { w: 6, h: 6 },
    properties: [
      { key: 'title', label: 'Judul', type: 'text', defaultValue: 'Hubungi Kami', group: 'Konten' },
      { key: 'description', label: 'Deskripsi', type: 'text', defaultValue: 'Kami siap membantu Anda. Isi formulir di bawah ini.', group: 'Konten' },
      { key: 'submitText', label: 'Teks Tombol', type: 'text', defaultValue: 'Kirim Pesan', group: 'Konten' },
      { key: 'accentColor', label: 'Warna Aksen', type: 'color', defaultValue: '#3b82f6', group: 'Style' },
      { key: 'backgroundColor', label: 'Warna Latar', type: 'color', defaultValue: '#f9fafb', group: 'Style' },
    ],
  },
  {
    type: 'search',
    name: 'Pencarian',
    icon: Search,
    category: 'forms',
    description: 'Kotak pencarian',
    defaultSize: { w: 6, h: 2 },
    minSize: { w: 3, h: 1 },
    properties: [
      { key: 'placeholder', label: 'Placeholder', type: 'text', defaultValue: 'Cari sesuatu...', group: 'Konten' },
      { key: 'buttonText', label: 'Teks Tombol', type: 'text', defaultValue: 'Cari', group: 'Konten' },
      { key: 'accentColor', label: 'Warna', type: 'color', defaultValue: '#3b82f6', group: 'Style' },
    ],
  },

  // ===== DATA =====
  {
    type: 'table',
    name: 'Tabel',
    icon: Table,
    category: 'data',
    description: 'Tabel data',
    defaultSize: { w: 12, h: 6 },
    minSize: { w: 6, h: 4 },
    properties: [
      { key: 'headers', label: 'Header (pisah koma)', type: 'text', defaultValue: 'Nama,Email,Status,Aksi', group: 'Konten' },
      { key: 'rows', label: 'Baris Data (JSON)', type: 'textarea', defaultValue: '[["Budi","budi@email.com","Aktif","Edit"],["Siti","siti@email.com","Pending","Edit"]]', group: 'Konten' },
      { key: 'striped', label: 'Bergaris', type: 'boolean', defaultValue: true, group: 'Style' },
      { key: 'bordered', label: 'Berbatas', type: 'boolean', defaultValue: true, group: 'Style' },
      { key: 'headerColor', label: 'Warna Header', type: 'color', defaultValue: '#f9fafb', group: 'Style' },
    ],
  },
  {
    type: 'statsCard',
    name: 'Kartu Statistik',
    icon: Hash,
    category: 'data',
    description: 'Kartu angka statistik',
    defaultSize: { w: 3, h: 3 },
    minSize: { w: 2, h: 2 },
    properties: [
      { key: 'label', label: 'Label', type: 'text', defaultValue: 'Total Penjualan', group: 'Konten' },
      { key: 'value', label: 'Nilai', type: 'text', defaultValue: 'Rp 125.000.000', group: 'Konten' },
      { key: 'change', label: 'Perubahan', type: 'text', defaultValue: '+12.5%', group: 'Konten' },
      { key: 'changeType', label: 'Tipe Perubahan', type: 'select', defaultValue: 'positive', options: [
        { label: 'Positif', value: 'positive' }, { label: 'Negatif', value: 'negative' }, { label: 'Netral', value: 'neutral' },
      ], group: 'Konten' },
      { key: 'backgroundColor', label: 'Warna Latar', type: 'color', defaultValue: '#ffffff', group: 'Style' },
      { key: 'accentColor', label: 'Warna Aksen', type: 'color', defaultValue: '#3b82f6', group: 'Style' },
    ],
  },
  {
    type: 'list',
    name: 'Daftar',
    icon: List,
    category: 'data',
    description: 'Daftar item',
    defaultSize: { w: 6, h: 4 },
    minSize: { w: 3, h: 2 },
    properties: [
      { key: 'items', label: 'Item (pisah baris)', type: 'textarea', defaultValue: 'Fitur pertama yang luar biasa\nFitur kedua yang menakjubkan\nFitur ketiga yang hebat\nFitur keempat yang canggih', group: 'Konten' },
      { key: 'listType', label: 'Tipe', type: 'select', defaultValue: 'check', options: [
        { label: 'Centang', value: 'check' }, { label: 'Bullet', value: 'bullet' },
        { label: 'Nomor', value: 'number' }, { label: 'Panah', value: 'arrow' },
      ], group: 'Style' },
      { key: 'color', label: 'Warna Ikon', type: 'color', defaultValue: '#10b981', group: 'Style' },
    ],
  },
  {
    type: 'cards',
    name: 'Grid Kartu',
    icon: LayoutGrid,
    category: 'data',
    description: 'Grid kartu informasi',
    defaultSize: { w: 12, h: 6 },
    minSize: { w: 6, h: 4 },
    properties: [
      { key: 'cards', label: 'Kartu (JSON)', type: 'textarea', defaultValue: '[{"title":"Cepat","desc":"Performa tinggi","icon":"zap"},{"title":"Aman","desc":"Keamanan terjamin","icon":"shield"},{"title":"Handal","desc":"Uptime 99.9%","icon":"check"}]', group: 'Konten' },
      { key: 'columns', label: 'Kolom', type: 'select', defaultValue: '3', options: [
        { label: '2', value: '2' }, { label: '3', value: '3' }, { label: '4', value: '4' },
      ], group: 'Layout' },
      { key: 'accentColor', label: 'Warna Aksen', type: 'color', defaultValue: '#3b82f6', group: 'Style' },
    ],
  },

  // ===== COMMERCE =====
  {
    type: 'priceCard',
    name: 'Kartu Harga',
    icon: CreditCard,
    category: 'commerce',
    description: 'Tabel harga produk/layanan',
    defaultSize: { w: 4, h: 8 },
    minSize: { w: 3, h: 6 },
    properties: [
      { key: 'planName', label: 'Nama Paket', type: 'text', defaultValue: 'Bisnis Pro', group: 'Konten' },
      { key: 'price', label: 'Harga', type: 'text', defaultValue: 'Rp 499.000', group: 'Konten' },
      { key: 'period', label: 'Periode', type: 'text', defaultValue: '/bulan', group: 'Konten' },
      { key: 'features', label: 'Fitur (pisah baris)', type: 'textarea', defaultValue: 'Unlimited POS\n50 Cabang\nLaporan Lengkap\nSupport 24/7\nAPI Access', group: 'Konten' },
      { key: 'buttonText', label: 'Teks Tombol', type: 'text', defaultValue: 'Mulai Sekarang', group: 'Konten' },
      { key: 'featured', label: 'Ditandai', type: 'boolean', defaultValue: true, group: 'Style' },
      { key: 'accentColor', label: 'Warna Aksen', type: 'color', defaultValue: '#3b82f6', group: 'Style' },
    ],
  },
  {
    type: 'cta',
    name: 'Call to Action',
    icon: Megaphone,
    category: 'commerce',
    description: 'Banner CTA',
    defaultSize: { w: 12, h: 4 },
    minSize: { w: 6, h: 3 },
    properties: [
      { key: 'title', label: 'Judul', type: 'text', defaultValue: 'Siap Mulai Bisnis Digital?', group: 'Konten' },
      { key: 'description', label: 'Deskripsi', type: 'text', defaultValue: 'Bergabung dengan ribuan bisnis yang sudah menggunakan platform kami.', group: 'Konten' },
      { key: 'buttonText', label: 'Teks Tombol', type: 'text', defaultValue: 'Daftar Gratis', group: 'Konten' },
      { key: 'backgroundGradient', label: 'Gradien', type: 'select', defaultValue: 'blue', options: [
        { label: 'Biru', value: 'blue' }, { label: 'Ungu', value: 'purple' },
        { label: 'Hijau', value: 'green' }, { label: 'Oranye', value: 'orange' }, { label: 'Merah Muda', value: 'pink' },
      ], group: 'Style' },
    ],
  },
  {
    type: 'productCard',
    name: 'Kartu Produk',
    icon: ShoppingCart,
    category: 'commerce',
    description: 'Kartu tampilan produk',
    defaultSize: { w: 3, h: 7 },
    minSize: { w: 3, h: 5 },
    properties: [
      { key: 'image', label: 'URL Gambar', type: 'text', defaultValue: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=300', group: 'Konten' },
      { key: 'name', label: 'Nama Produk', type: 'text', defaultValue: 'Headphone Premium', group: 'Konten' },
      { key: 'price', label: 'Harga', type: 'text', defaultValue: 'Rp 1.250.000', group: 'Konten' },
      { key: 'originalPrice', label: 'Harga Asli', type: 'text', defaultValue: 'Rp 1.750.000', group: 'Konten' },
      { key: 'rating', label: 'Rating', type: 'slider', defaultValue: 4.5, min: 0, max: 5, step: 0.5, group: 'Konten' },
      { key: 'badge', label: 'Badge', type: 'text', defaultValue: 'Diskon 30%', group: 'Konten' },
    ],
  },

  // ===== SOCIAL =====
  {
    type: 'testimonial',
    name: 'Testimoni',
    icon: MessageSquare,
    category: 'social',
    description: 'Kartu testimoni pelanggan',
    defaultSize: { w: 4, h: 5 },
    minSize: { w: 3, h: 4 },
    properties: [
      { key: 'text', label: 'Testimoni', type: 'textarea', defaultValue: 'Platform ini sangat membantu bisnis kami. Semuanya jadi lebih mudah dan terorganisir!', group: 'Konten' },
      { key: 'author', label: 'Nama', type: 'text', defaultValue: 'Ahmad Rizal', group: 'Konten' },
      { key: 'role', label: 'Jabatan', type: 'text', defaultValue: 'CEO, PT Maju Bersama', group: 'Konten' },
      { key: 'avatar', label: 'URL Avatar', type: 'text', defaultValue: '', group: 'Konten' },
      { key: 'rating', label: 'Rating', type: 'slider', defaultValue: 5, min: 1, max: 5, step: 1, group: 'Konten' },
    ],
  },
  {
    type: 'team',
    name: 'Anggota Tim',
    icon: Users,
    category: 'social',
    description: 'Kartu anggota tim',
    defaultSize: { w: 3, h: 6 },
    minSize: { w: 2, h: 4 },
    properties: [
      { key: 'name', label: 'Nama', type: 'text', defaultValue: 'Diana Putri', group: 'Konten' },
      { key: 'role', label: 'Jabatan', type: 'text', defaultValue: 'Product Manager', group: 'Konten' },
      { key: 'avatar', label: 'URL Foto', type: 'text', defaultValue: '', group: 'Konten' },
      { key: 'bio', label: 'Bio', type: 'textarea', defaultValue: 'Berpengalaman lebih dari 10 tahun di bidang teknologi.', group: 'Konten' },
      { key: 'accentColor', label: 'Warna Aksen', type: 'color', defaultValue: '#3b82f6', group: 'Style' },
    ],
  },
  {
    type: 'socialLinks',
    name: 'Link Sosial',
    icon: Link2,
    category: 'social',
    description: 'Ikon media sosial',
    defaultSize: { w: 6, h: 2 },
    minSize: { w: 3, h: 1 },
    properties: [
      { key: 'facebook', label: 'Facebook URL', type: 'text', defaultValue: '#', group: 'Links' },
      { key: 'instagram', label: 'Instagram URL', type: 'text', defaultValue: '#', group: 'Links' },
      { key: 'twitter', label: 'Twitter URL', type: 'text', defaultValue: '#', group: 'Links' },
      { key: 'linkedin', label: 'LinkedIn URL', type: 'text', defaultValue: '#', group: 'Links' },
      { key: 'youtube', label: 'YouTube URL', type: 'text', defaultValue: '', group: 'Links' },
      { key: 'size', label: 'Ukuran', type: 'slider', defaultValue: 32, min: 20, max: 56, group: 'Style' },
      { key: 'color', label: 'Warna', type: 'color', defaultValue: '#6b7280', group: 'Style' },
    ],
  },

  // ===== CHARTS =====
  {
    type: 'barChart',
    name: 'Grafik Batang',
    icon: BarChart3,
    category: 'charts',
    description: 'Grafik batang data',
    defaultSize: { w: 6, h: 5 },
    minSize: { w: 4, h: 3 },
    properties: [
      { key: 'title', label: 'Judul', type: 'text', defaultValue: 'Penjualan Bulanan', group: 'Konten' },
      { key: 'labels', label: 'Label (pisah koma)', type: 'text', defaultValue: 'Jan,Feb,Mar,Apr,Mei,Jun', group: 'Konten' },
      { key: 'values', label: 'Nilai (pisah koma)', type: 'text', defaultValue: '120,150,180,140,200,220', group: 'Konten' },
      { key: 'color', label: 'Warna', type: 'color', defaultValue: '#3b82f6', group: 'Style' },
    ],
  },
  {
    type: 'lineChart',
    name: 'Grafik Garis',
    icon: LineChart,
    category: 'charts',
    description: 'Grafik garis trend',
    defaultSize: { w: 6, h: 5 },
    minSize: { w: 4, h: 3 },
    properties: [
      { key: 'title', label: 'Judul', type: 'text', defaultValue: 'Tren Pendapatan', group: 'Konten' },
      { key: 'labels', label: 'Label (pisah koma)', type: 'text', defaultValue: 'Jan,Feb,Mar,Apr,Mei,Jun', group: 'Konten' },
      { key: 'values', label: 'Nilai (pisah koma)', type: 'text', defaultValue: '100,130,120,160,180,210', group: 'Konten' },
      { key: 'color', label: 'Warna', type: 'color', defaultValue: '#10b981', group: 'Style' },
      { key: 'fill', label: 'Isi Area', type: 'boolean', defaultValue: true, group: 'Style' },
    ],
  },
  {
    type: 'pieChart',
    name: 'Grafik Pie',
    icon: PieChart,
    category: 'charts',
    description: 'Grafik lingkaran',
    defaultSize: { w: 4, h: 5 },
    minSize: { w: 3, h: 3 },
    properties: [
      { key: 'title', label: 'Judul', type: 'text', defaultValue: 'Distribusi Penjualan', group: 'Konten' },
      { key: 'labels', label: 'Label (pisah koma)', type: 'text', defaultValue: 'Online,Toko,Marketplace,Grosir', group: 'Konten' },
      { key: 'values', label: 'Nilai (pisah koma)', type: 'text', defaultValue: '35,30,20,15', group: 'Konten' },
      { key: 'colors', label: 'Warna (pisah koma)', type: 'text', defaultValue: '#3b82f6,#10b981,#f59e0b,#ef4444', group: 'Style' },
    ],
  },

  // ===== MODULES (ERP) =====
  {
    type: 'posWidget',
    name: 'Widget POS',
    icon: ShoppingCart,
    category: 'modules',
    description: 'Widget ringkasan POS',
    defaultSize: { w: 6, h: 4 },
    minSize: { w: 4, h: 3 },
    properties: [
      { key: 'title', label: 'Judul', type: 'text', defaultValue: 'Ringkasan POS', group: 'Konten' },
      { key: 'showChart', label: 'Tampilkan Grafik', type: 'boolean', defaultValue: true, group: 'Pengaturan' },
      { key: 'accentColor', label: 'Warna Aksen', type: 'color', defaultValue: '#3b82f6', group: 'Style' },
    ],
  },
  {
    type: 'inventoryWidget',
    name: 'Widget Inventori',
    icon: Package,
    category: 'modules',
    description: 'Widget status inventori',
    defaultSize: { w: 6, h: 4 },
    minSize: { w: 4, h: 3 },
    properties: [
      { key: 'title', label: 'Judul', type: 'text', defaultValue: 'Status Inventori', group: 'Konten' },
      { key: 'showAlerts', label: 'Tampilkan Peringatan', type: 'boolean', defaultValue: true, group: 'Pengaturan' },
      { key: 'accentColor', label: 'Warna Aksen', type: 'color', defaultValue: '#10b981', group: 'Style' },
    ],
  },
  {
    type: 'financeWidget',
    name: 'Widget Keuangan',
    icon: Wallet,
    category: 'modules',
    description: 'Widget ringkasan keuangan',
    defaultSize: { w: 6, h: 4 },
    minSize: { w: 4, h: 3 },
    properties: [
      { key: 'title', label: 'Judul', type: 'text', defaultValue: 'Ringkasan Keuangan', group: 'Konten' },
      { key: 'showTrend', label: 'Tampilkan Tren', type: 'boolean', defaultValue: true, group: 'Pengaturan' },
      { key: 'accentColor', label: 'Warna Aksen', type: 'color', defaultValue: '#8b5cf6', group: 'Style' },
    ],
  },
  {
    type: 'hrisWidget',
    name: 'Widget HRIS',
    icon: UserCheck,
    category: 'modules',
    description: 'Widget ringkasan HRIS',
    defaultSize: { w: 6, h: 4 },
    minSize: { w: 4, h: 3 },
    properties: [
      { key: 'title', label: 'Judul', type: 'text', defaultValue: 'SDM & Kehadiran', group: 'Konten' },
      { key: 'showAttendance', label: 'Tampilkan Kehadiran', type: 'boolean', defaultValue: true, group: 'Pengaturan' },
      { key: 'accentColor', label: 'Warna Aksen', type: 'color', defaultValue: '#f59e0b', group: 'Style' },
    ],
  },
  {
    type: 'reportsWidget',
    name: 'Widget Laporan',
    icon: ClipboardList,
    category: 'modules',
    description: 'Widget laporan cepat',
    defaultSize: { w: 12, h: 5 },
    minSize: { w: 6, h: 3 },
    properties: [
      { key: 'title', label: 'Judul', type: 'text', defaultValue: 'Laporan Terkini', group: 'Konten' },
      { key: 'reportType', label: 'Tipe Laporan', type: 'select', defaultValue: 'sales', options: [
        { label: 'Penjualan', value: 'sales' }, { label: 'Inventori', value: 'inventory' },
        { label: 'Keuangan', value: 'finance' }, { label: 'SDM', value: 'hris' },
      ], group: 'Pengaturan' },
      { key: 'accentColor', label: 'Warna Aksen', type: 'color', defaultValue: '#6366f1', group: 'Style' },
    ],
  },

  // ===== INTEGRATION (ERP MODULE WIDGETS) =====
  {
    type: 'purchasingWidget',
    name: 'Widget Purchasing',
    icon: Truck,
    category: 'integration',
    description: 'Widget ringkasan pembelian & PO',
    defaultSize: { w: 6, h: 4 },
    minSize: { w: 4, h: 3 },
    properties: [
      { key: 'title', label: 'Judul', type: 'text', defaultValue: 'Status Pembelian', group: 'Konten' },
      { key: 'showPOList', label: 'Tampilkan Daftar PO', type: 'boolean', defaultValue: true, group: 'Pengaturan' },
      { key: 'showSupplier', label: 'Tampilkan Supplier', type: 'boolean', defaultValue: true, group: 'Pengaturan' },
      { key: 'accentColor', label: 'Warna Aksen', type: 'color', defaultValue: '#0ea5e9', group: 'Style' },
    ],
  },
  {
    type: 'crmWidget',
    name: 'Widget CRM',
    icon: Target,
    category: 'integration',
    description: 'Widget CRM & manajemen pelanggan',
    defaultSize: { w: 6, h: 4 },
    minSize: { w: 4, h: 3 },
    properties: [
      { key: 'title', label: 'Judul', type: 'text', defaultValue: 'Customer Insights', group: 'Konten' },
      { key: 'showSegments', label: 'Tampilkan Segmen', type: 'boolean', defaultValue: true, group: 'Pengaturan' },
      { key: 'showFunnel', label: 'Tampilkan Funnel', type: 'boolean', defaultValue: false, group: 'Pengaturan' },
      { key: 'accentColor', label: 'Warna Aksen', type: 'color', defaultValue: '#ec4899', group: 'Style' },
    ],
  },
  {
    type: 'loyaltyWidget',
    name: 'Widget Loyalty',
    icon: Award,
    category: 'integration',
    description: 'Widget program loyalty & member',
    defaultSize: { w: 6, h: 4 },
    minSize: { w: 4, h: 3 },
    properties: [
      { key: 'title', label: 'Judul', type: 'text', defaultValue: 'Program Loyalty', group: 'Konten' },
      { key: 'showPoints', label: 'Tampilkan Poin', type: 'boolean', defaultValue: true, group: 'Pengaturan' },
      { key: 'showTier', label: 'Tampilkan Tier', type: 'boolean', defaultValue: true, group: 'Pengaturan' },
      { key: 'accentColor', label: 'Warna Aksen', type: 'color', defaultValue: '#f59e0b', group: 'Style' },
    ],
  },
  {
    type: 'deliveryWidget',
    name: 'Widget Pengiriman',
    icon: Truck,
    category: 'integration',
    description: 'Pelacakan & status pengiriman',
    defaultSize: { w: 12, h: 4 },
    minSize: { w: 6, h: 3 },
    properties: [
      { key: 'title', label: 'Judul', type: 'text', defaultValue: 'Status Pengiriman', group: 'Konten' },
      { key: 'showMap', label: 'Tampilkan Peta', type: 'boolean', defaultValue: true, group: 'Pengaturan' },
      { key: 'showTimeline', label: 'Tampilkan Timeline', type: 'boolean', defaultValue: true, group: 'Pengaturan' },
      { key: 'accentColor', label: 'Warna Aksen', type: 'color', defaultValue: '#14b8a6', group: 'Style' },
    ],
  },
  {
    type: 'ticketingWidget',
    name: 'Widget Tiket',
    icon: Ticket,
    category: 'integration',
    description: 'Widget tiket & reservasi',
    defaultSize: { w: 6, h: 4 },
    minSize: { w: 4, h: 3 },
    properties: [
      { key: 'title', label: 'Judul', type: 'text', defaultValue: 'Tiket & Reservasi', group: 'Konten' },
      { key: 'showCalendar', label: 'Tampilkan Kalender', type: 'boolean', defaultValue: true, group: 'Pengaturan' },
      { key: 'accentColor', label: 'Warna Aksen', type: 'color', defaultValue: '#a855f7', group: 'Style' },
    ],
  },
  {
    type: 'fnbMenuWidget',
    name: 'Widget Menu F&B',
    icon: Utensils,
    category: 'integration',
    description: 'Menu restoran dari modul F&B',
    defaultSize: { w: 12, h: 6 },
    minSize: { w: 6, h: 4 },
    properties: [
      { key: 'title', label: 'Judul', type: 'text', defaultValue: 'Menu Kami', group: 'Konten' },
      { key: 'layout', label: 'Tampilan', type: 'select', defaultValue: 'grid', options: [
        { label: 'Grid', value: 'grid' }, { label: 'List', value: 'list' }, { label: 'Carousel', value: 'carousel' },
      ], group: 'Layout' },
      { key: 'showPrice', label: 'Tampilkan Harga', type: 'boolean', defaultValue: true, group: 'Pengaturan' },
      { key: 'showImage', label: 'Tampilkan Gambar', type: 'boolean', defaultValue: true, group: 'Pengaturan' },
      { key: 'columns', label: 'Kolom', type: 'select', defaultValue: '3', options: [
        { label: '2 Kolom', value: '2' }, { label: '3 Kolom', value: '3' }, { label: '4 Kolom', value: '4' },
      ], group: 'Layout' },
      { key: 'accentColor', label: 'Warna Aksen', type: 'color', defaultValue: '#ef4444', group: 'Style' },
    ],
  },
  {
    type: 'productCatalogWidget',
    name: 'Katalog Produk',
    icon: Store,
    category: 'integration',
    description: 'Katalog produk dari inventori',
    defaultSize: { w: 12, h: 6 },
    minSize: { w: 6, h: 4 },
    properties: [
      { key: 'title', label: 'Judul', type: 'text', defaultValue: 'Produk Kami', group: 'Konten' },
      { key: 'layout', label: 'Tampilan', type: 'select', defaultValue: 'grid', options: [
        { label: 'Grid', value: 'grid' }, { label: 'List', value: 'list' }, { label: 'Masonry', value: 'masonry' },
      ], group: 'Layout' },
      { key: 'showPrice', label: 'Tampilkan Harga', type: 'boolean', defaultValue: true, group: 'Pengaturan' },
      { key: 'showCategory', label: 'Filter Kategori', type: 'boolean', defaultValue: true, group: 'Pengaturan' },
      { key: 'showSearch', label: 'Kolom Pencarian', type: 'boolean', defaultValue: true, group: 'Pengaturan' },
      { key: 'showAddToCart', label: 'Tombol Keranjang', type: 'boolean', defaultValue: true, group: 'Pengaturan' },
      { key: 'columns', label: 'Kolom', type: 'select', defaultValue: '3', options: [
        { label: '2 Kolom', value: '2' }, { label: '3 Kolom', value: '3' }, { label: '4 Kolom', value: '4' },
      ], group: 'Layout' },
      { key: 'accentColor', label: 'Warna Aksen', type: 'color', defaultValue: '#6366f1', group: 'Style' },
    ],
  },
  {
    type: 'branchWidget',
    name: 'Widget Cabang',
    icon: Building2,
    category: 'integration',
    description: 'Lokasi cabang & info outlet',
    defaultSize: { w: 12, h: 5 },
    minSize: { w: 6, h: 3 },
    properties: [
      { key: 'title', label: 'Judul', type: 'text', defaultValue: 'Lokasi Kami', group: 'Konten' },
      { key: 'showMap', label: 'Tampilkan Peta', type: 'boolean', defaultValue: true, group: 'Pengaturan' },
      { key: 'showHours', label: 'Jam Operasional', type: 'boolean', defaultValue: true, group: 'Pengaturan' },
      { key: 'showContact', label: 'Info Kontak', type: 'boolean', defaultValue: true, group: 'Pengaturan' },
      { key: 'accentColor', label: 'Warna Aksen', type: 'color', defaultValue: '#0284c7', group: 'Style' },
    ],
  },
  {
    type: 'bookingWidget',
    name: 'Widget Booking',
    icon: Calendar,
    category: 'integration',
    description: 'Formulir booking & reservasi online',
    defaultSize: { w: 6, h: 5 },
    minSize: { w: 4, h: 4 },
    properties: [
      { key: 'title', label: 'Judul', type: 'text', defaultValue: 'Reservasi Online', group: 'Konten' },
      { key: 'showCalendar', label: 'Tampilkan Kalender', type: 'boolean', defaultValue: true, group: 'Pengaturan' },
      { key: 'showTimeSlots', label: 'Slot Waktu', type: 'boolean', defaultValue: true, group: 'Pengaturan' },
      { key: 'showGuestCount', label: 'Jumlah Tamu', type: 'boolean', defaultValue: true, group: 'Pengaturan' },
      { key: 'accentColor', label: 'Warna Aksen', type: 'color', defaultValue: '#8b5cf6', group: 'Style' },
    ],
  },
  {
    type: 'queueWidget',
    name: 'Widget Antrian',
    icon: ListChecks,
    category: 'integration',
    description: 'Widget antrian & nomor urut online',
    defaultSize: { w: 6, h: 4 },
    minSize: { w: 4, h: 3 },
    properties: [
      { key: 'title', label: 'Judul', type: 'text', defaultValue: 'Antrian Online', group: 'Konten' },
      { key: 'showEstimate', label: 'Estimasi Waktu', type: 'boolean', defaultValue: true, group: 'Pengaturan' },
      { key: 'showQR', label: 'QR Code', type: 'boolean', defaultValue: true, group: 'Pengaturan' },
      { key: 'accentColor', label: 'Warna Aksen', type: 'color', defaultValue: '#06b6d4', group: 'Style' },
    ],
  },
  {
    type: 'receiptWidget',
    name: 'Widget Struk',
    icon: Receipt,
    category: 'integration',
    description: 'Lookup struk & riwayat transaksi',
    defaultSize: { w: 6, h: 4 },
    minSize: { w: 4, h: 3 },
    properties: [
      { key: 'title', label: 'Judul', type: 'text', defaultValue: 'Cek Struk', group: 'Konten' },
      { key: 'showSearch', label: 'Kolom Pencarian', type: 'boolean', defaultValue: true, group: 'Pengaturan' },
      { key: 'accentColor', label: 'Warna Aksen', type: 'color', defaultValue: '#64748b', group: 'Style' },
    ],
  },
  {
    type: 'warehouseWidget',
    name: 'Widget Gudang',
    icon: Warehouse,
    category: 'integration',
    description: 'Status gudang & stok real-time',
    defaultSize: { w: 6, h: 4 },
    minSize: { w: 4, h: 3 },
    properties: [
      { key: 'title', label: 'Judul', type: 'text', defaultValue: 'Status Gudang', group: 'Konten' },
      { key: 'showChart', label: 'Tampilkan Grafik', type: 'boolean', defaultValue: true, group: 'Pengaturan' },
      { key: 'showAlerts', label: 'Peringatan Stok', type: 'boolean', defaultValue: true, group: 'Pengaturan' },
      { key: 'accentColor', label: 'Warna Aksen', type: 'color', defaultValue: '#059669', group: 'Style' },
    ],
  },
  {
    type: 'knowledgeBaseWidget',
    name: 'Widget Knowledge Base',
    icon: BookOpen,
    category: 'integration',
    description: 'Artikel & FAQ dari knowledge base',
    defaultSize: { w: 12, h: 5 },
    minSize: { w: 6, h: 3 },
    properties: [
      { key: 'title', label: 'Judul', type: 'text', defaultValue: 'Pusat Bantuan', group: 'Konten' },
      { key: 'showSearch', label: 'Kolom Pencarian', type: 'boolean', defaultValue: true, group: 'Pengaturan' },
      { key: 'showCategories', label: 'Tampilkan Kategori', type: 'boolean', defaultValue: true, group: 'Pengaturan' },
      { key: 'accentColor', label: 'Warna Aksen', type: 'color', defaultValue: '#7c3aed', group: 'Style' },
    ],
  },
  {
    type: 'apiConnectorWidget',
    name: 'API Connector',
    icon: Plug,
    category: 'integration',
    description: 'Widget konektor API eksternal',
    defaultSize: { w: 6, h: 4 },
    minSize: { w: 4, h: 3 },
    properties: [
      { key: 'title', label: 'Judul', type: 'text', defaultValue: 'Data Eksternal', group: 'Konten' },
      { key: 'apiUrl', label: 'URL API', type: 'text', defaultValue: '', placeholder: 'https://api.example.com/data', group: 'API' },
      { key: 'method', label: 'Method', type: 'select', defaultValue: 'GET', options: [
        { label: 'GET', value: 'GET' }, { label: 'POST', value: 'POST' },
      ], group: 'API' },
      { key: 'displayType', label: 'Tampilan', type: 'select', defaultValue: 'table', options: [
        { label: 'Tabel', value: 'table' }, { label: 'List', value: 'list' }, { label: 'Kartu', value: 'card' }, { label: 'JSON', value: 'json' },
      ], group: 'Layout' },
      { key: 'refreshInterval', label: 'Refresh (detik)', type: 'number', defaultValue: 0, min: 0, max: 3600, group: 'API' },
      { key: 'accentColor', label: 'Warna Aksen', type: 'color', defaultValue: '#475569', group: 'Style' },
    ],
  },
];

export function getWidgetDefinition(type: string): WidgetDefinition | undefined {
  return widgetRegistry.find(w => w.type === type);
}

export function getWidgetsByCategory(category: WidgetCategory): WidgetDefinition[] {
  return widgetRegistry.filter(w => w.category === category);
}

export function getAllCategories(): WidgetCategory[] {
  return [...new Set(widgetRegistry.map(w => w.category))];
}
