import { KBArticle, CategoryInfo, KBCategory } from './types';

export const CATEGORIES: CategoryInfo[] = [
  { id: 'getting-started', name: 'Memulai', description: 'Panduan dasar untuk pengguna baru', icon: 'Rocket', color: 'blue', gradient: 'from-blue-500 to-blue-600' },
  { id: 'core-system', name: 'Core System', description: 'Dashboard, cabang, dan pengaturan', icon: 'LayoutDashboard', color: 'indigo', gradient: 'from-indigo-500 to-indigo-600' },
  { id: 'operations', name: 'Operasional', description: 'POS, inventory, warehouse, manufaktur', icon: 'Package', color: 'emerald', gradient: 'from-emerald-500 to-emerald-600' },
  { id: 'finance', name: 'Keuangan', description: 'Invoice, laporan keuangan, pajak', icon: 'Wallet', color: 'amber', gradient: 'from-amber-500 to-amber-600' },
  { id: 'hr', name: 'SDM & HRIS', description: 'Karyawan, payroll, KPI, cuti', icon: 'UserCheck', color: 'cyan', gradient: 'from-cyan-500 to-cyan-600' },
  { id: 'sales-marketing', name: 'Sales & Marketing', description: 'CRM, SFA, kampanye, promosi', icon: 'Briefcase', color: 'pink', gradient: 'from-pink-500 to-pink-600' },
  { id: 'logistics', name: 'Logistik', description: 'Fleet, transportasi, pengiriman', icon: 'Truck', color: 'orange', gradient: 'from-orange-500 to-orange-600' },
  { id: 'integration', name: 'Integrasi', description: 'WhatsApp, marketplace, API', icon: 'Plug', color: 'green', gradient: 'from-green-500 to-green-600' },
  { id: 'analytics', name: 'Laporan & Analitik', description: 'Report, audit, data analytics', icon: 'BarChart3', color: 'purple', gradient: 'from-purple-500 to-purple-600' },
  { id: 'system', name: 'Pengaturan Sistem', description: 'Modul, role, konfigurasi global', icon: 'Settings', color: 'slate', gradient: 'from-slate-500 to-slate-600' },
];

export const KB_ARTICLES: KBArticle[] = [
  // ── GETTING STARTED ──
  {
    slug: 'onboarding-guide',
    title: 'Panduan Memulai Bedagang ERP',
    subtitle: 'Langkah pertama menggunakan platform',
    category: 'getting-started', module: 'onboarding', icon: 'Rocket', color: 'blue', gradient: 'from-blue-500 to-indigo-600',
    overview: 'Selamat datang di Bedagang ERP! Platform all-in-one untuk mengelola seluruh aspek bisnis Anda. Panduan ini membantu Anda memulai dari registrasi, verifikasi KYB, hingga dashboard pertama kali.',
    keyFeatures: ['Registrasi dan KYB dalam 4 langkah', 'Auto-provisioning berdasarkan jenis bisnis', 'Dashboard disesuaikan per modul', 'Multi-cabang dari hari pertama', 'Role-based access control'],
    businessFlow: {
      title: 'Alur Onboarding', description: 'Dari registrasi hingga siap pakai',
      steps: [
        { id: 1, label: 'Registrasi', description: 'Buat akun email & password', actor: 'User', action: 'Isi form registrasi' },
        { id: 2, label: 'KYB', description: 'Lengkapi profil bisnis 6 tahap', actor: 'User', action: 'Upload dokumen & data' },
        { id: 3, label: 'Verifikasi', description: 'Admin review kelengkapan', actor: 'Admin', action: 'Review & approve' },
        { id: 4, label: 'Provisioning', description: 'Sistem setup tenant & modul', actor: 'System', action: 'Clone settings' },
        { id: 5, label: 'Aktivasi', description: 'Akun aktif, masuk dashboard', actor: 'User', action: 'Login & mulai' },
      ],
    },
    sequenceDiagram: [
      { from: 'User', to: 'System', action: 'Register', description: 'Buat akun baru', type: 'request' },
      { from: 'System', to: 'User', action: 'Verifikasi Email', description: 'Kirim email verifikasi', type: 'notify' },
      { from: 'User', to: 'System', action: 'Submit KYB', description: 'Isi 6 langkah + upload', type: 'request' },
      { from: 'System', to: 'Admin', action: 'Notif Review', description: 'KYB baru perlu direview', type: 'notify' },
      { from: 'Admin', to: 'System', action: 'Approve', description: 'Verifikasi data & dokumen', type: 'action' },
      { from: 'System', to: 'System', action: 'Provisioning', description: 'Buat tenant, branch, clone', type: 'action' },
      { from: 'System', to: 'User', action: 'Aktif', description: 'Akun siap digunakan', type: 'response' },
    ],
    usageGuide: [
      { step: 1, title: 'Registrasi', description: 'Isi data dasar akun.', substeps: ['Nama lengkap', 'Email aktif', 'Password min 8 karakter'] },
      { step: 2, title: 'Verifikasi Email', description: 'Cek inbox, klik link verifikasi.' },
      { step: 3, title: 'KYB 6 Tahap', description: 'Isi profil bisnis selengkap mungkin.', substeps: ['Pilih kategori bisnis', 'Data perusahaan (nama, NPWP)', 'Upload dokumen legal', 'Struktur bisnis', 'Kontak PIC', 'Review & Submit'] },
      { step: 4, title: 'Tunggu Verifikasi', description: 'Admin review dalam 1-3 hari kerja.' },
      { step: 5, title: 'Mulai Gunakan', description: 'Login & konfigurasi awal.', substeps: ['Atur info toko/cabang', 'Tambah produk pertama', 'Undang karyawan'] },
    ],
    tips: ['Siapkan dokumen legal sebelum KYB', 'Pilih kategori bisnis yang tepat', 'Gunakan email perusahaan'],
    faqs: [
      { question: 'Berapa lama verifikasi KYB?', answer: '1-3 hari kerja. Notifikasi via email.' },
      { question: 'Bisa ubah jenis bisnis?', answer: 'Ya, hubungi admin. Modul disesuaikan ulang.' },
      { question: 'Ada trial period?', answer: 'Ya, 11 modul Basic gratis. Add-on Pro berbayar.' },
    ],
    relatedModules: ['dashboard', 'settings', 'branches'],
    userRoles: [
      { role: 'Owner', access: 'Full akses semua fitur' },
      { role: 'Admin', access: 'Management & konfigurasi' },
      { role: 'Staff', access: 'Akses sesuai role' },
    ],
    lastUpdated: '2026-03-01', readTime: '8 menit', difficulty: 'beginner',
  },
  {
    slug: 'navigasi-platform',
    title: 'Navigasi & Antarmuka Platform',
    subtitle: 'Sidebar, dashboard, menu, dan shortcut',
    category: 'getting-started', module: 'navigation', icon: 'Compass', color: 'blue', gradient: 'from-blue-400 to-cyan-500',
    overview: 'Platform memiliki 3 layout: HQ, Branch, dan Admin. Setiap layout punya sidebar yang disesuaikan dengan modul & role. Pelajari navigasi, pencarian, dan notifikasi.',
    keyFeatures: ['Sidebar collapse/expand', 'Pencarian global', 'Notifikasi real-time', 'Responsive design'],
    businessFlow: {
      title: 'Alur Navigasi', description: 'Interaksi user dengan platform',
      steps: [
        { id: 1, label: 'Login', description: 'Masuk platform', actor: 'User', action: 'Input credentials' },
        { id: 2, label: 'Redirect', description: 'Arah ke layout sesuai role', actor: 'System', action: 'Check role' },
        { id: 3, label: 'Sidebar', description: 'Navigasi modul', actor: 'User', action: 'Klik menu' },
        { id: 4, label: 'Content', description: 'Halaman modul tampil', actor: 'System', action: 'Render page' },
      ],
    },
    sequenceDiagram: [
      { from: 'User', to: 'System', action: 'Login', description: 'Email & password', type: 'request' },
      { from: 'System', to: 'User', action: 'Redirect', description: 'Ke /hq/home atau /dashboard', type: 'response' },
      { from: 'User', to: 'System', action: 'Navigate', description: 'Klik menu sidebar', type: 'request' },
      { from: 'System', to: 'User', action: 'Render', description: 'Tampilkan halaman', type: 'response' },
    ],
    usageGuide: [
      { step: 1, title: 'Sidebar', description: 'Menu di sisi kiri.', substeps: ['Klik panah untuk collapse/expand', 'Menu grouped by kategori', 'Aktif = warna biru'] },
      { step: 2, title: 'Pencarian', description: 'Search bar di header.' },
      { step: 3, title: 'Notifikasi', description: 'Ikon lonceng di kanan atas.' },
      { step: 4, title: 'Profil', description: 'Avatar kanan atas untuk settings.' },
    ],
    tips: ['Collapse sidebar untuk area lebih luas', 'Gunakan search untuk navigasi cepat', 'Cek notifikasi berkala'],
    faqs: [
      { question: 'Menu tidak muncul?', answer: 'Menu tampil berdasarkan modul aktif & role. Hubungi admin.' },
      { question: 'Bisa dari mobile?', answer: 'Ya, responsive. Disarankan landscape untuk mobile.' },
    ],
    relatedModules: ['dashboard', 'settings'],
    userRoles: [{ role: 'Semua', access: 'Navigasi sesuai role' }],
    lastUpdated: '2026-03-01', readTime: '5 menit', difficulty: 'beginner',
  },

  // ── CORE SYSTEM ──
  {
    slug: 'dashboard-operasional',
    title: 'Dashboard Operasional',
    subtitle: 'Pusat monitoring bisnis real-time',
    category: 'core-system', module: 'dashboard', icon: 'BarChart3', color: 'indigo', gradient: 'from-indigo-500 to-indigo-600',
    overview: 'Dashboard Operasional adalah pusat kontrol. Ringkasan penjualan, performa cabang, stok kritis, keuangan, dan aktivitas terbaru dalam satu tampilan real-time.',
    keyFeatures: ['Ringkasan penjualan harian/mingguan/bulanan', 'Performa cabang ranking', 'Alert stok minimum & expired', 'Grafik tren revenue', 'Quick action shortcuts'],
    businessFlow: {
      title: 'Alur Monitoring', description: 'Data mengalir ke dashboard',
      steps: [
        { id: 1, label: 'Transaksi', description: 'POS mencatat penjualan', actor: 'Cashier', action: 'Proses jual' },
        { id: 2, label: 'Sync', description: 'Data sync ke server', actor: 'System', action: 'Real-time sync' },
        { id: 3, label: 'Aggregasi', description: 'Data diagregasi', actor: 'System', action: 'Calculate metrics' },
        { id: 4, label: 'Visualisasi', description: 'Tampil di dashboard', actor: 'System', action: 'Render charts' },
        { id: 5, label: 'Decision', description: 'Manager ambil keputusan', actor: 'Manager', action: 'Analisa & act' },
      ],
    },
    sequenceDiagram: [
      { from: 'POS', to: 'Server', action: 'Sync', description: 'Data penjualan real-time', type: 'request' },
      { from: 'Server', to: 'DB', action: 'Aggregate', description: 'Hitung metrik', type: 'action' },
      { from: 'Manager', to: 'Dashboard', action: 'Open', description: 'Buka dashboard', type: 'request' },
      { from: 'Dashboard', to: 'API', action: 'Fetch', description: 'Ambil data', type: 'request' },
      { from: 'API', to: 'Dashboard', action: 'Data', description: 'Return metrics', type: 'response' },
    ],
    usageGuide: [
      { step: 1, title: 'Akses Dashboard', description: 'Klik Dashboard Operasional di sidebar.' },
      { step: 2, title: 'Kartu Ringkasan', description: 'Bagian atas: Revenue, Transaksi, Avg Ticket, Growth.' },
      { step: 3, title: 'Grafik', description: 'Tren revenue, ranking cabang, top produk.' },
      { step: 4, title: 'Alerts', description: 'Perhatikan badge merah/kuning.' },
    ],
    tips: ['Cek dashboard setiap pagi', 'Perhatikan stok kritis', 'Bandingkan performa cabang'],
    faqs: [
      { question: 'Data seberapa real-time?', answer: 'Refresh 60 detik otomatis + manual refresh.' },
      { question: 'Bisa filter per cabang?', answer: 'Ya, gunakan dropdown filter.' },
    ],
    relatedModules: ['branches', 'pos', 'finance', 'inventory'],
    userRoles: [
      { role: 'Owner/HQ Admin', access: 'Semua data global' },
      { role: 'Manager', access: 'Data cabang terkelola' },
    ],
    lastUpdated: '2026-03-01', readTime: '6 menit', difficulty: 'beginner',
  },
  {
    slug: 'manajemen-cabang',
    title: 'Manajemen Cabang',
    subtitle: 'Kelola dan monitor semua outlet',
    category: 'core-system', module: 'branches', icon: 'Building2', color: 'violet', gradient: 'from-violet-500 to-violet-600',
    overview: 'Kelola semua outlet dari satu tempat. Tambah cabang, atur pengaturan per cabang, monitor performa, dan kelola inventori antar cabang.',
    keyFeatures: ['Daftar cabang real-time', 'Pengaturan unik per cabang', 'Performa KPI cabang', 'Setup cabang otomatis', 'Transfer antar cabang'],
    businessFlow: {
      title: 'Lifecycle Cabang', description: 'Dari pembuatan hingga monitoring',
      steps: [
        { id: 1, label: 'Buat', description: 'Tambah data cabang', actor: 'HQ Admin', action: 'Input data' },
        { id: 2, label: 'Setup', description: 'Konfigurasi awal', actor: 'System', action: 'Clone settings' },
        { id: 3, label: 'Assign', description: 'Tunjuk branch manager', actor: 'HQ Admin', action: 'Assign user' },
        { id: 4, label: 'Operasi', description: 'Cabang beroperasi', actor: 'Staff', action: 'Daily ops' },
        { id: 5, label: 'Monitor', description: 'HQ pantau performa', actor: 'HQ Admin', action: 'Review KPI' },
      ],
    },
    sequenceDiagram: [
      { from: 'HQ Admin', to: 'System', action: 'Create Branch', description: 'Input data cabang', type: 'request' },
      { from: 'System', to: 'DB', action: 'Setup', description: 'Clone settings & modules', type: 'action' },
      { from: 'HQ Admin', to: 'System', action: 'Assign Manager', description: 'Tunjuk PIC', type: 'action' },
      { from: 'System', to: 'Manager', action: 'Notif', description: 'Anda Branch Manager', type: 'notify' },
    ],
    usageGuide: [
      { step: 1, title: 'Daftar Cabang', description: 'Cabang → Daftar Cabang di sidebar.' },
      { step: 2, title: 'Tambah Baru', description: 'Klik + Tambah Cabang, isi data.' },
      { step: 3, title: 'Performa', description: 'Lihat ranking KPI cabang.' },
      { step: 4, title: 'Konfigurasi', description: 'Klik cabang untuk detail & settings.' },
    ],
    tips: ['Assign manager sebelum cabang operasi', 'Gunakan performa untuk identifikasi masalah'],
    faqs: [
      { question: 'Max cabang?', answer: 'Tidak ada batas teknis. Tergantung paket.' },
      { question: 'Produk otomatis?', answer: 'Ya, master produk HQ otomatis tersedia di cabang baru.' },
    ],
    relatedModules: ['dashboard', 'users', 'inventory'],
    userRoles: [
      { role: 'Owner/HQ Admin', access: 'CRUD semua cabang' },
      { role: 'Branch Manager', access: 'Kelola cabang assigned' },
    ],
    lastUpdated: '2026-03-01', readTime: '7 menit', difficulty: 'beginner',
  },
  {
    slug: 'modul-management',
    title: 'Modul Management',
    subtitle: 'Aktifkan modul sesuai kebutuhan bisnis',
    category: 'core-system', module: 'settings', icon: 'Package', color: 'slate', gradient: 'from-slate-500 to-slate-600',
    overview: 'Arsitektur modular. 11 modul Basic gratis, 13+ Add-on Pro berbayar. Setiap modul punya dependency yang divalidasi otomatis saat aktivasi.',
    keyFeatures: ['11 modul Basic gratis', '13+ modul Add-on Pro', 'Dependency validation', 'Toggle on/off tanpa hilang data'],
    businessFlow: {
      title: 'Aktivasi Modul', description: 'Cara mengaktifkan modul baru',
      steps: [
        { id: 1, label: 'Browse', description: 'Lihat katalog modul', actor: 'Owner', action: 'Buka Modul Management' },
        { id: 2, label: 'Check', description: 'Cek dependensi', actor: 'System', action: 'Validate prerequisites' },
        { id: 3, label: 'Activate', description: 'Toggle ON', actor: 'Owner', action: 'Klik toggle' },
        { id: 4, label: 'Ready', description: 'Muncul di sidebar', actor: 'System', action: 'Enable features' },
      ],
    },
    sequenceDiagram: [
      { from: 'Owner', to: 'System', action: 'Toggle Module', description: 'Aktifkan HRIS', type: 'request' },
      { from: 'System', to: 'System', action: 'Check Deps', description: 'HRIS needs Employees', type: 'action' },
      { from: 'System', to: 'DB', action: 'Enable', description: 'Set isEnabled = true', type: 'action' },
      { from: 'System', to: 'Owner', action: 'Success', description: 'Modul aktif', type: 'response' },
    ],
    usageGuide: [
      { step: 1, title: 'Buka Modul Management', description: 'Pengaturan → Modul Manajemen.' },
      { step: 2, title: 'Basic Modules', description: '11 modul gratis sudah aktif.' },
      { step: 3, title: 'Add-on Pro', description: 'Toggle untuk aktifkan. Dependency otomatis dicek.' },
    ],
    tips: ['Aktifkan bertahap sesuai fase bisnis', 'Nonaktifkan modul tidak hapus data'],
    faqs: [
      { question: 'Data hilang jika nonaktif?', answer: 'Tidak. Data tetap ada, hanya akses fitur dinonaktifkan.' },
      { question: 'Dependency contoh?', answer: 'Kitchen butuh POS. HRIS butuh Employees. Loyalty butuh Customers.' },
    ],
    relatedModules: ['settings', 'dashboard'],
    userRoles: [{ role: 'Owner/Super Admin', access: 'Full toggle modul' }],
    lastUpdated: '2026-03-01', readTime: '5 menit', difficulty: 'intermediate',
  },

  // ── OPERATIONS ──
  {
    slug: 'point-of-sale',
    title: 'Point of Sale (POS)',
    subtitle: 'Sistem kasir dan penjualan outlet',
    category: 'operations', module: 'pos', icon: 'ShoppingCart', color: 'blue', gradient: 'from-blue-500 to-blue-600',
    overview: 'POS adalah jantung operasional outlet. Proses penjualan, terima pembayaran (tunai, QRIS, e-wallet, kartu), cetak struk, kelola shift kasir. Terintegrasi inventory & keuangan.',
    keyFeatures: ['Interface kasir cepat', 'Multi-payment', 'Shift management', 'Cetak struk thermal', 'Auto-deduct stok', 'Void & retur', 'Loyalty & promo'],
    businessFlow: {
      title: 'Alur Transaksi POS', description: 'Buka kasir sampai tutup shift',
      steps: [
        { id: 1, label: 'Buka Shift', description: 'Login & input saldo awal', actor: 'Kasir', action: 'Start shift' },
        { id: 2, label: 'Input Order', description: 'Scan/pilih produk', actor: 'Kasir', action: 'Add to cart' },
        { id: 3, label: 'Diskon', description: 'Apply promo/voucher', actor: 'System', action: 'Auto-apply' },
        { id: 4, label: 'Bayar', description: 'Proses pembayaran', actor: 'Kasir', action: 'Select payment' },
        { id: 5, label: 'Struk', description: 'Print receipt', actor: 'System', action: 'Generate & print' },
        { id: 6, label: 'Update Stok', description: 'Stok berkurang', actor: 'System', action: 'Deduct inventory' },
        { id: 7, label: 'Tutup Shift', description: 'Rekonsiliasi kas', actor: 'Kasir', action: 'Count & close' },
      ],
    },
    sequenceDiagram: [
      { from: 'Kasir', to: 'POS', action: 'Buka Shift', description: 'Input saldo awal', type: 'request' },
      { from: 'Kasir', to: 'POS', action: 'Add Item', description: 'Scan barcode', type: 'request' },
      { from: 'POS', to: 'Inventory', action: 'Check Stock', description: 'Validasi stok', type: 'request' },
      { from: 'Kasir', to: 'POS', action: 'Pay', description: 'Pilih metode bayar', type: 'request' },
      { from: 'POS', to: 'Gateway', action: 'Process', description: 'Proses payment', type: 'request' },
      { from: 'Gateway', to: 'POS', action: 'OK', description: 'Pembayaran berhasil', type: 'response' },
      { from: 'POS', to: 'Inventory', action: 'Deduct', description: 'Kurangi stok', type: 'action' },
      { from: 'POS', to: 'Finance', action: 'Record', description: 'Catat pendapatan', type: 'action' },
    ],
    usageGuide: [
      { step: 1, title: 'Buka Shift', description: 'Login, klik Buka Kasir, input saldo awal.' },
      { step: 2, title: 'Penjualan', description: 'Scan/pilih produk, atur qty.', substeps: ['Scan barcode atau cari manual', 'Atur jumlah', 'Tambah catatan jika perlu'] },
      { step: 3, title: 'Pembayaran', description: 'Pilih metode: Tunai/QRIS/e-Wallet/Kartu.' },
      { step: 4, title: 'Cetak Struk', description: 'Otomatis tercetak atau kirim WA.' },
      { step: 5, title: 'Tutup Shift', description: 'Hitung fisik kas, bandingkan expected.' },
    ],
    tips: ['Selalu buka shift dulu', 'Gunakan keyboard shortcut', 'Rekonsiliasi kas setiap tutup shift'],
    faqs: [
      { question: 'Internet mati?', answer: 'POS support offline. Sync otomatis saat koneksi kembali.' },
      { question: 'Void transaksi?', answer: 'Supervisor bisa void. Stok dikembalikan otomatis.' },
      { question: 'Status: Open, Closed, Void?', answer: 'Open: proses. Closed: selesai. Void: dibatalkan.' },
    ],
    relatedModules: ['inventory', 'finance', 'customers', 'kitchen'],
    userRoles: [
      { role: 'Kasir', access: 'Proses penjualan & tutup shift' },
      { role: 'Supervisor', access: 'Void, override harga' },
      { role: 'Owner', access: 'Full + laporan POS' },
    ],
    lastUpdated: '2026-03-01', readTime: '10 menit', difficulty: 'beginner',
  },
  {
    slug: 'warehouse-inventory',
    title: 'Warehouse & Inventory',
    subtitle: 'Stok, gudang, transfer, stock opname',
    category: 'operations', module: 'inventory', icon: 'Package', color: 'emerald', gradient: 'from-emerald-500 to-emerald-600',
    overview: 'Mengelola seluruh stok: pembelian (PO), penerimaan barang, transfer antar gudang/cabang, stock opname, alert stok minimum, tracking expired, dan pergerakan stok.',
    keyFeatures: ['Multi-warehouse', 'Purchase Order & Goods Receipt', 'Transfer stok', 'Stock opname', 'Alert minimum & expired', 'Price tiers', 'Movement history'],
    businessFlow: {
      title: 'Siklus Inventori', description: 'Dari pembelian hingga penjualan',
      steps: [
        { id: 1, label: 'PO', description: 'Order ke supplier', actor: 'Staff', action: 'Create PO' },
        { id: 2, label: 'Approve', description: 'Manager approve', actor: 'Manager', action: 'Approve PO' },
        { id: 3, label: 'Receive', description: 'Terima barang', actor: 'Warehouse', action: 'Goods Receipt' },
        { id: 4, label: 'Stok +', description: 'Stok bertambah', actor: 'System', action: 'Update stock' },
        { id: 5, label: 'Transfer', description: 'Kirim ke cabang', actor: 'Warehouse', action: 'Create transfer' },
        { id: 6, label: 'Sell', description: 'Stok terjual via POS', actor: 'POS', action: 'Auto-deduct' },
        { id: 7, label: 'Opname', description: 'Verifikasi fisik', actor: 'Staff', action: 'Count' },
      ],
    },
    sequenceDiagram: [
      { from: 'Staff', to: 'System', action: 'Create PO', description: 'PO ke supplier', type: 'request' },
      { from: 'Manager', to: 'System', action: 'Approve', description: 'PO disetujui', type: 'action' },
      { from: 'Warehouse', to: 'System', action: 'Goods Receipt', description: 'Terima barang', type: 'request' },
      { from: 'System', to: 'Inventory', action: 'Update Stock', description: 'Stok +', type: 'action' },
      { from: 'Warehouse', to: 'System', action: 'Transfer', description: 'Kirim ke cabang', type: 'request' },
      { from: 'System', to: 'Cabang', action: 'Notify', description: 'Transfer masuk', type: 'notify' },
    ],
    usageGuide: [
      { step: 1, title: 'Dashboard', description: 'Ringkasan stok semua gudang.' },
      { step: 2, title: 'Master Produk', description: 'Tambah/edit produk + SKU, kategori, harga.' },
      { step: 3, title: 'Purchase Order', description: 'Buat PO → pilih supplier → tambah item.' },
      { step: 4, title: 'Goods Receipt', description: 'Input penerimaan dari PO.' },
      { step: 5, title: 'Transfer', description: 'Buat transfer: Draft → Approve → Ship → Receive.' },
      { step: 6, title: 'Stock Opname', description: 'Buat sesi, hitung fisik, reconcile.' },
    ],
    tips: ['Set minimum stok untuk alert otomatis', 'Stock opname min 1x/bulan', 'Gunakan barcode/SKU'],
    faqs: [
      { question: 'Warehouse vs Location?', answer: 'Warehouse = gudang fisik. Location = zona/rak di dalam warehouse.' },
      { question: 'Alur transfer?', answer: 'Draft → Pending → Approved → In Transit → Received.' },
      { question: 'Import produk massal?', answer: 'Ya, upload CSV/Excel di Master Produk.' },
    ],
    relatedModules: ['products', 'pos', 'finance'],
    userRoles: [
      { role: 'Inventory Staff', access: 'CRUD stok, PO' },
      { role: 'Manager', access: 'Approve PO & transfer' },
      { role: 'Owner', access: 'Full + laporan' },
    ],
    lastUpdated: '2026-03-01', readTime: '12 menit', difficulty: 'intermediate',
  },
  {
    slug: 'manufacturing',
    title: 'Manufacturing',
    subtitle: 'Work Order, BOM, QC, OEE Analytics',
    category: 'operations', module: 'manufacturing', icon: 'Factory', color: 'gray', gradient: 'from-gray-600 to-gray-700',
    overview: 'Modul Manufacturing untuk produksi. Work Order, Bill of Materials, Routing, Work Center, Quality Control, OEE Analytics, Production Costing, Waste tracking.',
    keyFeatures: ['Work Order', 'BOM multi-level', 'Routing & Work Center', 'Quality Control', 'OEE Analytics', 'Production Costing', 'Waste tracking'],
    businessFlow: {
      title: 'Alur Produksi', description: 'Material → finished goods',
      steps: [
        { id: 1, label: 'BOM', description: 'Define material list', actor: 'Engineer', action: 'Create BOM' },
        { id: 2, label: 'Plan', description: 'Rencana produksi', actor: 'Planner', action: 'Production plan' },
        { id: 3, label: 'WO', description: 'Order produksi', actor: 'Supervisor', action: 'Create WO' },
        { id: 4, label: 'Issue', description: 'Keluarkan material', actor: 'Warehouse', action: 'Issue materials' },
        { id: 5, label: 'Produce', description: 'Proses produksi', actor: 'Operator', action: 'Execute WO' },
        { id: 6, label: 'QC', description: 'Inspeksi kualitas', actor: 'QC', action: 'Inspect' },
        { id: 7, label: 'Receipt', description: 'Finished goods ke stok', actor: 'Warehouse', action: 'Receipt FG' },
      ],
    },
    sequenceDiagram: [
      { from: 'Planner', to: 'System', action: 'Create WO', description: 'Work Order baru', type: 'request' },
      { from: 'System', to: 'Inventory', action: 'Check Material', description: 'Cek bahan', type: 'request' },
      { from: 'Operator', to: 'System', action: 'Start', description: 'Mulai produksi', type: 'action' },
      { from: 'Operator', to: 'System', action: 'Complete', description: 'Selesai', type: 'action' },
      { from: 'QC', to: 'System', action: 'Inspect', description: 'Pass/Fail', type: 'action' },
      { from: 'System', to: 'Inventory', action: 'Receipt', description: 'FG masuk stok', type: 'action' },
    ],
    usageGuide: [
      { step: 1, title: 'Setup BOM', description: 'Buat Bill of Materials per produk.' },
      { step: 2, title: 'Work Order', description: 'Buat WO, set qty & deadline.' },
      { step: 3, title: 'Produksi', description: 'Eksekusi WO di lantai produksi.' },
      { step: 4, title: 'QC', description: 'Inspeksi kualitas output.' },
      { step: 5, title: 'OEE', description: 'Monitor efektivitas di dashboard.' },
    ],
    tips: ['Update BOM jika formula berubah', 'Gunakan OEE identifikasi bottleneck', 'Track waste untuk optimasi biaya'],
    faqs: [
      { question: 'Apa itu OEE?', answer: 'Overall Equipment Effectiveness = Availability x Performance x Quality.' },
      { question: 'Multi-level BOM?', answer: 'Ya, mendukung sub-assembly.' },
    ],
    relatedModules: ['inventory', 'products', 'reports'],
    userRoles: [
      { role: 'Planner', access: 'Create WO & plan' },
      { role: 'Operator', access: 'Execute & report' },
      { role: 'QC', access: 'Inspeksi' },
    ],
    lastUpdated: '2026-03-01', readTime: '10 menit', difficulty: 'advanced',
  },
  {
    slug: 'kitchen-fnb',
    title: 'Kitchen & Table Management',
    subtitle: 'Dapur, meja, reservasi untuk F&B',
    category: 'operations', module: 'kitchen', icon: 'ChefHat', color: 'red', gradient: 'from-red-500 to-orange-500',
    overview: 'Untuk F&B: Kitchen Display System, manajemen meja, reservasi. Order dari POS otomatis ke KDS untuk chef.',
    keyFeatures: ['Kitchen Display System', 'Floor plan meja', 'Reservasi', 'Status tracking', 'Integrasi POS'],
    businessFlow: {
      title: 'Alur Pesanan F&B', description: 'Order hingga served',
      steps: [
        { id: 1, label: 'Order', description: 'Pelanggan pesan', actor: 'Kasir', action: 'Input POS' },
        { id: 2, label: 'KDS', description: 'Ticket ke dapur', actor: 'System', action: 'Push ke KDS' },
        { id: 3, label: 'Cook', description: 'Chef masak', actor: 'Chef', action: 'Preparing' },
        { id: 4, label: 'Ready', description: 'Siap saji', actor: 'Chef', action: 'Mark ready' },
        { id: 5, label: 'Serve', description: 'Antar ke meja', actor: 'Waiter', action: 'Mark served' },
      ],
    },
    sequenceDiagram: [
      { from: 'Kasir', to: 'POS', action: 'Order', description: 'Input pesanan + nomor meja', type: 'request' },
      { from: 'POS', to: 'Kitchen', action: 'Ticket', description: 'Kirim ke KDS', type: 'action' },
      { from: 'Chef', to: 'KDS', action: 'Start', description: 'New → Preparing', type: 'action' },
      { from: 'Chef', to: 'KDS', action: 'Done', description: 'Preparing → Ready', type: 'action' },
      { from: 'KDS', to: 'Waiter', action: 'Alert', description: 'Makanan siap', type: 'notify' },
      { from: 'Waiter', to: 'System', action: 'Served', description: 'Ready → Served', type: 'action' },
    ],
    usageGuide: [
      { step: 1, title: 'Setup Meja', description: 'Tambah meja + kapasitas.' },
      { step: 2, title: 'Reservasi', description: 'Input tamu, tanggal, jam.' },
      { step: 3, title: 'KDS', description: 'Chef proses order di Kitchen Display.' },
      { step: 4, title: 'Status', description: 'Update setiap tahap.' },
    ],
    tips: ['Atur prioritas by waktu masuk', 'Pakai tablet di dapur', 'Warna status = identifikasi cepat'],
    faqs: [
      { question: 'Status apa saja?', answer: 'New → Preparing → Ready → Served → Cancelled.' },
      { question: 'Print kitchen ticket?', answer: 'Ya, printer dapur terpisah dari struk kasir.' },
    ],
    relatedModules: ['pos', 'tables', 'reservations'],
    userRoles: [
      { role: 'Kitchen Staff', access: 'Update order' },
      { role: 'Kasir', access: 'Input order' },
    ],
    lastUpdated: '2026-03-01', readTime: '7 menit', difficulty: 'beginner',
  },

  // ── FINANCE ──
  {
    slug: 'finance-pro',
    title: 'Keuangan Pro',
    subtitle: 'Akuntansi, invoice, P&L, arus kas',
    category: 'finance', module: 'finance_pro', icon: 'Wallet', color: 'amber', gradient: 'from-amber-500 to-amber-600',
    overview: 'Fitur akuntansi lengkap: invoice, laba rugi, arus kas, piutang/hutang, anggaran, pajak. Terintegrasi POS & HRIS.',
    keyFeatures: ['Dashboard keuangan', 'Invoice auto-numbering', 'Laba Rugi', 'Arus Kas', 'Piutang/Hutang', 'Budget tracking', 'Pajak', 'Export PDF/Excel'],
    businessFlow: {
      title: 'Alur Keuangan', description: 'Transaksi → laporan',
      steps: [
        { id: 1, label: 'Transaksi', description: 'Revenue POS, expense manual', actor: 'System/Staff', action: 'Record' },
        { id: 2, label: 'Kategorisasi', description: 'Alokasi ke akun', actor: 'Finance', action: 'Categorize' },
        { id: 3, label: 'Invoice', description: 'Buat tagihan', actor: 'Finance', action: 'Generate invoice' },
        { id: 4, label: 'Rekonsiliasi', description: 'Cocokkan bank', actor: 'Finance', action: 'Reconcile' },
        { id: 5, label: 'Laporan', description: 'P&L, cash flow', actor: 'System', action: 'Calculate' },
        { id: 6, label: 'Pajak', description: 'Hitung kewajiban', actor: 'System', action: 'Tax calc' },
      ],
    },
    sequenceDiagram: [
      { from: 'POS', to: 'Finance', action: 'Revenue', description: 'Pendapatan otomatis', type: 'action' },
      { from: 'Finance', to: 'System', action: 'Invoice', description: 'Buat tagihan', type: 'request' },
      { from: 'System', to: 'Customer', action: 'Send', description: 'Kirim invoice', type: 'notify' },
      { from: 'Customer', to: 'System', action: 'Pay', description: 'Bayar tagihan', type: 'action' },
      { from: 'Finance', to: 'System', action: 'Report', description: 'Generate P&L', type: 'request' },
      { from: 'System', to: 'Finance', action: 'P&L', description: 'Laporan siap', type: 'response' },
    ],
    usageGuide: [
      { step: 1, title: 'Dashboard', description: 'Ringkasan revenue, expenses, profit.' },
      { step: 2, title: 'Invoice', description: 'Buat tagihan baru.' },
      { step: 3, title: 'Pengeluaran', description: 'Catat pengeluaran + bukti.' },
      { step: 4, title: 'Laporan', description: 'P&L, Cash Flow, atau Neraca.', substeps: ['Filter periode', 'Bandingkan vs sebelumnya', 'Export PDF/Excel'] },
      { step: 5, title: 'Budget', description: 'Buat budget per dept, monitor realisasi.' },
    ],
    tips: ['Kategorisasi benar = laporan akurat', 'Kirim invoice tepat waktu', 'Review budget vs aktual bulanan'],
    faqs: [
      { question: 'Revenue POS otomatis?', answer: 'Ya, transaksi closed otomatis jadi revenue.' },
      { question: 'Beda Lite vs Pro?', answer: 'Lite: transaksi & harian. Pro: full akuntansi, invoice, P&L.' },
      { question: 'e-Faktur?', answer: 'Ya, mendukung e-Invoice format pajak Indonesia.' },
    ],
    relatedModules: ['pos', 'reports', 'hris'],
    userRoles: [
      { role: 'Finance Staff', access: 'CRUD transaksi & invoice' },
      { role: 'Manager', access: 'Approve & laporan' },
      { role: 'Owner', access: 'Full akses keuangan' },
    ],
    lastUpdated: '2026-03-01', readTime: '10 menit', difficulty: 'intermediate',
  },

  // ── HR ──
  {
    slug: 'hris-overview',
    title: 'HRIS - Manajemen SDM',
    subtitle: 'Karyawan, organisasi, KPI, payroll, cuti',
    category: 'hr', module: 'hris', icon: 'UserCheck', color: 'cyan', gradient: 'from-cyan-500 to-cyan-600',
    overview: 'Solusi lengkap SDM: database karyawan, struktur organisasi, KPI, payroll, cuti, kehadiran, ESS, MSS, industrial relations, workforce analytics, engagement, travel & expense, project management.',
    keyFeatures: ['Database Karyawan', 'Struktur Organisasi & Job Grading', 'KPI & Performance', 'Payroll custom', 'Cuti multi-level approval', 'Kehadiran & Shift', 'ESS & MSS', 'Industrial Relations', 'Workforce Analytics', 'Travel & Expense', 'Project Management'],
    businessFlow: {
      title: 'Lifecycle Karyawan', description: 'Recruit → retire',
      steps: [
        { id: 1, label: 'Recruit', description: 'Input karyawan baru', actor: 'HR', action: 'Create employee' },
        { id: 2, label: 'Onboard', description: 'Kontrak & assign', actor: 'HR', action: 'Contract + org' },
        { id: 3, label: 'Daily', description: 'Absensi, cuti, klaim', actor: 'Employee', action: 'Clock in, request' },
        { id: 4, label: 'Performance', description: 'Review KPI', actor: 'Manager', action: 'Evaluate' },
        { id: 5, label: 'Payroll', description: 'Gaji bulanan', actor: 'HR', action: 'Calculate & pay' },
        { id: 6, label: 'Analytics', description: 'Workforce data', actor: 'HR Manager', action: 'Dashboard' },
      ],
    },
    sequenceDiagram: [
      { from: 'HR', to: 'System', action: 'Add Employee', description: 'Input data karyawan', type: 'request' },
      { from: 'HR', to: 'System', action: 'Contract', description: 'PKWT/PKWTT', type: 'request' },
      { from: 'Employee', to: 'ESS', action: 'Clock In', description: 'Absensi GPS', type: 'request' },
      { from: 'ESS', to: 'System', action: 'Geofence', description: 'Validasi lokasi', type: 'action' },
      { from: 'Employee', to: 'ESS', action: 'Leave', description: 'Ajukan cuti', type: 'request' },
      { from: 'System', to: 'Manager', action: 'Approve', description: 'Perlu approval', type: 'notify' },
      { from: 'HR', to: 'System', action: 'Payroll', description: 'Run payroll', type: 'request' },
      { from: 'System', to: 'Employees', action: 'Payslip', description: 'Slip gaji', type: 'notify' },
    ],
    usageGuide: [
      { step: 1, title: 'Setup Organisasi', description: 'Buat hierarki & job grade.', substeps: ['Struktur: BOD → Divisi → Dept', 'Job Grade: G1-G10 + salary range'] },
      { step: 2, title: 'Input Karyawan', description: 'Database Karyawan → Tambah.', substeps: ['Data pribadi, keluarga, pendidikan', 'Buat kontrak kerja'] },
      { step: 3, title: 'Kehadiran', description: 'Setup shift, geofence, metode absensi.' },
      { step: 4, title: 'KPI', description: 'Buat indikator per posisi.' },
      { step: 5, title: 'Payroll', description: 'Setup komponen gaji, run payroll bulanan.', substeps: ['Komponen: tunjangan, potongan, BPJS', 'Calculate → Review → Approve → Distribute'] },
    ],
    tips: ['Setup org sebelum import karyawan', 'Bulk upload via Excel', 'Payroll H-3 sebelum gajian', 'Review KPI tiap kuartal'],
    faqs: [
      { question: 'Sub-modul HRIS?', answer: 'Karyawan, Org, KPI, Payroll, Cuti, Kehadiran, ESS, MSS, IR, Workforce, Engagement, Travel, Project.' },
      { question: 'Geofence absensi?', answer: 'Karyawan harus clock in dalam radius GPS yang ditentukan.' },
      { question: 'Custom payroll?', answer: 'Ya, setiap komponen bisa diatur: fixed, %, atau formula custom.' },
      { question: 'ESS vs MSS?', answer: 'ESS: karyawan lihat info & ajukan. MSS: manager approve & review tim.' },
    ],
    relatedModules: ['employees', 'finance_pro', 'reports'],
    userRoles: [
      { role: 'HR Staff', access: 'CRUD karyawan, payroll' },
      { role: 'Manager', access: 'MSS, approve, KPI' },
      { role: 'Employee', access: 'ESS, absensi, cuti' },
      { role: 'Owner', access: 'Full + analytics' },
    ],
    lastUpdated: '2026-03-01', readTime: '15 menit', difficulty: 'intermediate',
  },

  // ── SALES & MARKETING ──
  {
    slug: 'crm-sfa',
    title: 'CRM & Sales Force Automation',
    subtitle: 'Pipeline, customer 360, leads, visits',
    category: 'sales-marketing', module: 'crm', icon: 'Briefcase', color: 'pink', gradient: 'from-pink-500 to-pink-600',
    overview: 'Solusi terintegrasi CRM & SFA. Leads, pipeline, customer 360°, kunjungan GPS, quotation, target, insentif, AI lead scoring, tiket & SLA.',
    keyFeatures: ['Lead & Pipeline', 'Customer 360°', 'Visit GPS tracking', 'Quotation & Order', 'Target & Achievement', 'Incentive & Commission', 'AI Lead Scoring', 'Ticket & SLA'],
    businessFlow: {
      title: 'Sales Pipeline', description: 'Lead → closed deal',
      steps: [
        { id: 1, label: 'Lead', description: 'Lead baru masuk', actor: 'System', action: 'Capture' },
        { id: 2, label: 'Qualify', description: 'Evaluasi + AI score', actor: 'Sales', action: 'Score' },
        { id: 3, label: 'Opportunity', description: 'Convert ke opportunity', actor: 'Sales', action: 'Create opp' },
        { id: 4, label: 'Visit', description: 'Kunjungi prospect', actor: 'Salesman', action: 'GPS check-in' },
        { id: 5, label: 'Quote', description: 'Kirim penawaran', actor: 'Sales', action: 'Create quotation' },
        { id: 6, label: 'Negotiate', description: 'Negosiasi', actor: 'Sales', action: 'Revise' },
        { id: 7, label: 'Close', description: 'Won / Lost', actor: 'Sales', action: 'Update status' },
      ],
    },
    sequenceDiagram: [
      { from: 'Marketing', to: 'System', action: 'New Lead', description: 'Dari campaign', type: 'request' },
      { from: 'System', to: 'AI', action: 'Score', description: 'AI analisa lead', type: 'action' },
      { from: 'Sales', to: 'System', action: 'Opportunity', description: 'Convert lead', type: 'action' },
      { from: 'Salesman', to: 'System', action: 'Visit', description: 'GPS check-in', type: 'request' },
      { from: 'Sales', to: 'System', action: 'Quotation', description: 'Buat penawaran', type: 'request' },
      { from: 'System', to: 'Prospect', action: 'Send', description: 'Kirim via email/WA', type: 'notify' },
      { from: 'Sales', to: 'System', action: 'Won', description: 'Deal berhasil', type: 'action' },
    ],
    usageGuide: [
      { step: 1, title: 'Leads', description: 'Tab Leads → filter, convert berkualitas.' },
      { step: 2, title: 'Customer 360°', description: 'Profil lengkap: history, interaksi, revenue.' },
      { step: 3, title: 'Kunjungan', description: 'Salesman check-in GPS.' },
      { step: 4, title: 'Quotation', description: 'Buat & kirim penawaran.' },
      { step: 5, title: 'Target', description: 'Monitor achievement vs target.' },
    ],
    tips: ['Follow up lead <24 jam', 'Gunakan AI scoring', 'Track semua interaksi', 'Review target mingguan'],
    faqs: [
      { question: 'AI Lead Scoring?', answer: 'AI analisa data historis, scoring 0-100.' },
      { question: 'Beda CRM vs SFA?', answer: 'CRM: relasi (360°, ticket). SFA: aktivitas sales (lead, visit, target).' },
    ],
    relatedModules: ['marketing', 'whatsapp_business', 'finance_pro'],
    userRoles: [
      { role: 'Sales', access: 'CRUD leads, opp, quotation' },
      { role: 'Sales Manager', access: 'Target, approval' },
      { role: 'CS', access: 'Tickets, communication' },
    ],
    lastUpdated: '2026-03-01', readTime: '12 menit', difficulty: 'intermediate',
  },

  // ── LOGISTICS ──
  {
    slug: 'fleet-management',
    title: 'Fleet Management System',
    subtitle: 'Kendaraan, driver, GPS, maintenance',
    category: 'logistics', module: 'fms', icon: 'Truck', color: 'orange', gradient: 'from-orange-500 to-orange-600',
    overview: 'Kelola armada: GPS real-time, maintenance scheduling, BBM monitoring, inspeksi, driver management, cost analysis. Untuk logistik & distribusi.',
    keyFeatures: ['Dashboard fleet', 'GPS Live Tracking', 'Maintenance scheduling', 'BBM monitoring', 'Driver scoring', 'Inspeksi digital', 'Geofence', 'Cost analytics'],
    businessFlow: {
      title: 'Fleet Lifecycle', description: 'Kendaraan dari akuisisi hingga disposal',
      steps: [
        { id: 1, label: 'Register', description: 'Daftarkan kendaraan', actor: 'Admin', action: 'Input data kendaraan' },
        { id: 2, label: 'Assign', description: 'Tugaskan driver', actor: 'Manager', action: 'Assign driver' },
        { id: 3, label: 'Operate', description: 'Kendaraan beroperasi', actor: 'Driver', action: 'Daily trips' },
        { id: 4, label: 'Track', description: 'GPS monitoring', actor: 'System', action: 'Real-time tracking' },
        { id: 5, label: 'Maintain', description: 'Service berkala', actor: 'Admin', action: 'Schedule maintenance' },
        { id: 6, label: 'Analyze', description: 'Analisa biaya & efisiensi', actor: 'Manager', action: 'Review analytics' },
      ],
    },
    sequenceDiagram: [
      { from: 'Admin', to: 'System', action: 'Add Vehicle', description: 'Daftarkan kendaraan', type: 'request' },
      { from: 'Admin', to: 'System', action: 'Assign Driver', description: 'Tugaskan driver', type: 'action' },
      { from: 'Driver', to: 'System', action: 'Start Trip', description: 'Mulai perjalanan', type: 'request' },
      { from: 'System', to: 'GPS', action: 'Track', description: 'GPS real-time', type: 'action' },
      { from: 'System', to: 'Admin', action: 'Maintenance Due', description: 'Alert service', type: 'notify' },
      { from: 'Admin', to: 'System', action: 'Schedule', description: 'Jadwalkan maintenance', type: 'action' },
    ],
    usageGuide: [
      { step: 1, title: 'Kendaraan', description: 'Daftarkan semua kendaraan + plat, tipe, tahun.' },
      { step: 2, title: 'Driver', description: 'Input data driver + SIM, skor.' },
      { step: 3, title: 'GPS Live', description: 'Monitor lokasi kendaraan real-time.' },
      { step: 4, title: 'Maintenance', description: 'Jadwalkan service + reminder otomatis.' },
      { step: 5, title: 'BBM', description: 'Catat pengisian BBM, monitor konsumsi.' },
      { step: 6, title: 'Analytics', description: 'Analisa biaya, efisiensi, driver score.' },
    ],
    tips: ['Set reminder maintenance otomatis', 'Monitor BBM anomali = indikasi masalah', 'Gunakan geofence untuk area operasi'],
    faqs: [
      { question: 'GPS device apa?', answer: 'Mendukung berbagai GPS tracker via API integration.' },
      { question: 'Driver scoring?', answer: 'Berdasarkan ketepatan waktu, pelanggaran, efisiensi BBM.' },
    ],
    relatedModules: ['tms', 'reports'],
    userRoles: [
      { role: 'Fleet Admin', access: 'CRUD kendaraan & driver' },
      { role: 'Driver', access: 'Start/end trip, fuel log' },
      { role: 'Manager', access: 'Analytics & approval' },
    ],
    lastUpdated: '2026-03-01', readTime: '10 menit', difficulty: 'intermediate',
  },
  {
    slug: 'transport-management',
    title: 'Transportation Management',
    subtitle: 'Shipment, dispatch, carrier, tracking',
    category: 'logistics', module: 'tms', icon: 'Send', color: 'lime', gradient: 'from-lime-500 to-lime-600',
    overview: 'Kelola pengiriman end-to-end: shipment, trip planning, dispatch, carrier management, route optimization, billing, dan SLA delivery.',
    keyFeatures: ['Shipment management', 'Trip planning', 'Auto-dispatch', 'Carrier management', 'Route optimization', 'Delivery SLA', 'Freight billing', 'Zone & rate cards'],
    businessFlow: {
      title: 'Alur Pengiriman', description: 'Order → delivery → POD',
      steps: [
        { id: 1, label: 'Order', description: 'Order masuk perlu kirim', actor: 'System', action: 'Create shipment' },
        { id: 2, label: 'Plan', description: 'Rencanakan trip', actor: 'Dispatcher', action: 'Create trip' },
        { id: 3, label: 'Dispatch', description: 'Assign carrier/driver', actor: 'Dispatcher', action: 'Dispatch' },
        { id: 4, label: 'Transit', description: 'Dalam perjalanan', actor: 'Driver', action: 'GPS tracking' },
        { id: 5, label: 'Deliver', description: 'Serah terima', actor: 'Driver', action: 'POD capture' },
        { id: 6, label: 'Bill', description: 'Tagihan pengiriman', actor: 'System', action: 'Generate freight bill' },
      ],
    },
    sequenceDiagram: [
      { from: 'System', to: 'TMS', action: 'New Shipment', description: 'Order perlu kirim', type: 'request' },
      { from: 'Dispatcher', to: 'TMS', action: 'Plan Trip', description: 'Buat rute trip', type: 'action' },
      { from: 'TMS', to: 'Driver', action: 'Dispatch', description: 'Assign pengiriman', type: 'notify' },
      { from: 'Driver', to: 'TMS', action: 'Pickup', description: 'Barang diambil', type: 'action' },
      { from: 'TMS', to: 'Customer', action: 'Tracking', description: 'Update status', type: 'notify' },
      { from: 'Driver', to: 'TMS', action: 'Delivered', description: 'POD captured', type: 'action' },
    ],
    usageGuide: [
      { step: 1, title: 'Shipment', description: 'Buat shipment dari order.' },
      { step: 2, title: 'Trip', description: 'Gabungkan beberapa shipment jadi 1 trip.' },
      { step: 3, title: 'Dispatch', description: 'Assign ke carrier atau driver internal.' },
      { step: 4, title: 'Tracking', description: 'Monitor real-time via GPS.' },
      { step: 5, title: 'SLA', description: 'Pantau delivery vs SLA commitment.' },
    ],
    tips: ['Gabungkan shipment untuk efisiensi', 'Set SLA per zona', 'Monitor carrier score'],
    faqs: [
      { question: 'Integrasi kurir?', answer: 'Mendukung integrasi dengan carrier via API.' },
      { question: 'Rate card?', answer: 'Set tarif per zona, berat, volume.' },
    ],
    relatedModules: ['fms', 'inventory'],
    userRoles: [
      { role: 'Dispatcher', access: 'Plan & dispatch' },
      { role: 'Driver', access: 'Tracking & POD' },
      { role: 'Manager', access: 'Analytics & billing' },
    ],
    lastUpdated: '2026-03-01', readTime: '8 menit', difficulty: 'intermediate',
  },

  // ── INTEGRATION ──
  {
    slug: 'whatsapp-business',
    title: 'WhatsApp Business',
    subtitle: 'Broadcast, template, automasi WA',
    category: 'integration', module: 'whatsapp_business', icon: 'MessageCircle', color: 'green', gradient: 'from-green-500 to-green-600',
    overview: 'Integrasi WhatsApp Business untuk komunikasi pelanggan. Broadcast promo, template pesan, notifikasi otomatis (invoice, order, dll).',
    keyFeatures: ['Broadcast massal', 'Template pesan', 'Notifikasi otomatis', 'Integrasi CRM', 'Chat management'],
    businessFlow: {
      title: 'Alur WhatsApp Business', description: 'Setup hingga broadcast',
      steps: [
        { id: 1, label: 'Connect', description: 'Hubungkan nomor WA', actor: 'Admin', action: 'API setup' },
        { id: 2, label: 'Template', description: 'Buat template pesan', actor: 'Admin', action: 'Create template' },
        { id: 3, label: 'Segment', description: 'Pilih target', actor: 'Marketing', action: 'Select audience' },
        { id: 4, label: 'Broadcast', description: 'Kirim pesan', actor: 'Marketing', action: 'Send broadcast' },
        { id: 5, label: 'Track', description: 'Monitor delivery', actor: 'System', action: 'Track status' },
      ],
    },
    sequenceDiagram: [
      { from: 'Admin', to: 'System', action: 'Connect WA', description: 'Setup WA Business API', type: 'request' },
      { from: 'Marketing', to: 'System', action: 'Broadcast', description: 'Kirim ke segment', type: 'request' },
      { from: 'System', to: 'WA API', action: 'Send', description: 'Batch send', type: 'action' },
      { from: 'WA API', to: 'Customer', action: 'Message', description: 'Pesan terkirim', type: 'notify' },
    ],
    usageGuide: [
      { step: 1, title: 'Setup', description: 'Hubungkan WA Business API.' },
      { step: 2, title: 'Template', description: 'Buat template yang di-approve Meta.' },
      { step: 3, title: 'Broadcast', description: 'Pilih template + audience, kirim.' },
    ],
    tips: ['Template harus di-approve Meta dulu', 'Jangan spam, bisa kena ban', 'Personalisasi pesan'],
    faqs: [
      { question: 'Perlu WA Business API?', answer: 'Ya, harus punya akun WA Business API (berbayar dari Meta).' },
      { question: 'Bisa auto-reply?', answer: 'Ya, konfigurasi auto-reply di pengaturan.' },
    ],
    relatedModules: ['crm', 'marketing'],
    userRoles: [
      { role: 'Admin', access: 'Setup & config' },
      { role: 'Marketing', access: 'Broadcast & template' },
    ],
    lastUpdated: '2026-03-01', readTime: '6 menit', difficulty: 'intermediate',
  },
  {
    slug: 'marketplace-integration',
    title: 'Marketplace Integration',
    subtitle: 'Tokopedia, Shopee, sync produk & order',
    category: 'integration', module: 'marketplace_integration', icon: 'ShoppingBag', color: 'blue', gradient: 'from-blue-500 to-cyan-600',
    overview: 'Sinkronisasi produk dan order dari marketplace (Tokopedia, Shopee, dll). Kelola multi-channel dari satu dashboard.',
    keyFeatures: ['Sync produk 2 arah', 'Sync order otomatis', 'Multi-channel dashboard', 'Inventory sync', 'Price management'],
    businessFlow: {
      title: 'Alur Marketplace', description: 'Connect → sync → manage',
      steps: [
        { id: 1, label: 'Connect', description: 'Hubungkan toko', actor: 'Admin', action: 'API auth' },
        { id: 2, label: 'Sync Produk', description: 'Push produk ke marketplace', actor: 'System', action: 'Sync catalog' },
        { id: 3, label: 'Order Masuk', description: 'Order dari marketplace', actor: 'Customer', action: 'Buy' },
        { id: 4, label: 'Process', description: 'Proses order di Bedagang', actor: 'Staff', action: 'Fulfill order' },
        { id: 5, label: 'Ship', description: 'Kirim & update tracking', actor: 'Staff', action: 'Ship & update' },
      ],
    },
    sequenceDiagram: [
      { from: 'Admin', to: 'System', action: 'Connect', description: 'Auth ke Tokopedia', type: 'request' },
      { from: 'System', to: 'Marketplace', action: 'Sync Products', description: 'Push catalog', type: 'action' },
      { from: 'Marketplace', to: 'System', action: 'New Order', description: 'Order masuk', type: 'notify' },
      { from: 'Staff', to: 'System', action: 'Process', description: 'Fulfill & ship', type: 'action' },
      { from: 'System', to: 'Marketplace', action: 'Update', description: 'Update status & tracking', type: 'action' },
    ],
    usageGuide: [
      { step: 1, title: 'Connect', description: 'Hubungkan toko marketplace via API.' },
      { step: 2, title: 'Sync', description: 'Push produk, set harga per channel.' },
      { step: 3, title: 'Orders', description: 'Lihat & proses order dari semua channel.' },
    ],
    tips: ['Sync harga bisa beda per channel', 'Monitor stok agar tidak oversell'],
    faqs: [
      { question: 'Marketplace apa saja?', answer: 'Tokopedia, Shopee. Lazada & Bukalapak dalam pengembangan.' },
      { question: 'Stok otomatis sync?', answer: 'Ya, stok di-sync real-time ke semua channel.' },
    ],
    relatedModules: ['inventory', 'products'],
    userRoles: [
      { role: 'Admin', access: 'Setup channels' },
      { role: 'Staff', access: 'Process orders' },
    ],
    lastUpdated: '2026-03-01', readTime: '7 menit', difficulty: 'intermediate',
  },

  // ── ANALYTICS ──
  {
    slug: 'laporan-analitik',
    title: 'Laporan & Analitik',
    subtitle: 'Report konsolidasi, penjualan, stok, keuangan',
    category: 'analytics', module: 'reports', icon: 'BarChart3', color: 'purple', gradient: 'from-purple-500 to-purple-600',
    overview: 'Pusat laporan konsolidasi dari semua modul. Laporan penjualan, stok, keuangan, karyawan. Filter per periode, cabang, kategori. Export PDF & Excel.',
    keyFeatures: ['Laporan Penjualan', 'Laporan Konsolidasi', 'Laporan Stok', 'Laporan Keuangan', 'Filter multi-dimensi', 'Export PDF/Excel', 'Scheduled reports'],
    businessFlow: {
      title: 'Alur Pelaporan', description: 'Data → insight → action',
      steps: [
        { id: 1, label: 'Data', description: 'Kumpulkan dari semua modul', actor: 'System', action: 'Aggregate' },
        { id: 2, label: 'Filter', description: 'Pilih dimensi laporan', actor: 'User', action: 'Set filters' },
        { id: 3, label: 'Generate', description: 'Proses laporan', actor: 'System', action: 'Calculate' },
        { id: 4, label: 'Visualize', description: 'Tampilkan charts & tabel', actor: 'System', action: 'Render' },
        { id: 5, label: 'Export', description: 'Download PDF/Excel', actor: 'User', action: 'Export' },
      ],
    },
    sequenceDiagram: [
      { from: 'User', to: 'System', action: 'Open Report', description: 'Pilih jenis laporan', type: 'request' },
      { from: 'User', to: 'System', action: 'Filter', description: 'Set periode & cabang', type: 'action' },
      { from: 'System', to: 'DB', action: 'Query', description: 'Aggregate data', type: 'request' },
      { from: 'DB', to: 'System', action: 'Data', description: 'Return results', type: 'response' },
      { from: 'System', to: 'User', action: 'Report', description: 'Display charts', type: 'response' },
    ],
    usageGuide: [
      { step: 1, title: 'Pilih Laporan', description: 'Sidebar → Laporan → pilih jenis.' },
      { step: 2, title: 'Filter', description: 'Set periode, cabang, kategori.' },
      { step: 3, title: 'Analisa', description: 'Baca grafik dan tabel data.' },
      { step: 4, title: 'Export', description: 'Download PDF atau Excel.' },
    ],
    tips: ['Gunakan filter untuk deep-dive', 'Bandingkan periode untuk tren', 'Export untuk presentasi'],
    faqs: [
      { question: 'Bisa schedule report otomatis?', answer: 'Ya, set jadwal laporan untuk dikirim via email.' },
      { question: 'Data real-time?', answer: 'Laporan menggunakan data terkini saat di-generate.' },
    ],
    relatedModules: ['dashboard', 'finance_pro', 'pos', 'inventory'],
    userRoles: [
      { role: 'Manager+', access: 'Semua jenis laporan' },
      { role: 'Staff', access: 'Laporan area kerjanya' },
    ],
    lastUpdated: '2026-03-01', readTime: '6 menit', difficulty: 'beginner',
  },
  {
    slug: 'audit-log',
    title: 'Audit Log',
    subtitle: 'Riwayat aktivitas dan keamanan sistem',
    category: 'analytics', module: 'audit', icon: 'Shield', color: 'slate', gradient: 'from-slate-600 to-gray-700',
    overview: 'Catat semua aktivitas pengguna di sistem. Siapa melakukan apa, kapan, dan di modul mana. Penting untuk compliance dan keamanan.',
    keyFeatures: ['Log semua aktivitas user', 'Filter by user, module, action', 'Timestamp detail', 'Export audit trail', 'Compliance ready'],
    businessFlow: {
      title: 'Alur Audit', description: 'Capture → store → review',
      steps: [
        { id: 1, label: 'Action', description: 'User lakukan aktivitas', actor: 'User', action: 'Create/update/delete' },
        { id: 2, label: 'Capture', description: 'Sistem catat log', actor: 'System', action: 'Log to audit' },
        { id: 3, label: 'Store', description: 'Simpan permanen', actor: 'System', action: 'Persist' },
        { id: 4, label: 'Review', description: 'Admin review log', actor: 'Admin', action: 'Search & filter' },
      ],
    },
    sequenceDiagram: [
      { from: 'User', to: 'System', action: 'Action', description: 'CRUD operation', type: 'request' },
      { from: 'System', to: 'Audit Log', action: 'Record', description: 'Log user, action, timestamp', type: 'action' },
      { from: 'Admin', to: 'Audit Log', action: 'Search', description: 'Filter & review', type: 'request' },
      { from: 'Audit Log', to: 'Admin', action: 'Results', description: 'Activity history', type: 'response' },
    ],
    usageGuide: [
      { step: 1, title: 'Buka Audit Log', description: 'Sidebar → Audit Log.' },
      { step: 2, title: 'Filter', description: 'By user, module, date range, action type.' },
      { step: 3, title: 'Review', description: 'Lihat detail setiap entry.' },
      { step: 4, title: 'Export', description: 'Download untuk compliance report.' },
    ],
    tips: ['Review audit log berkala', 'Cek aktivitas mencurigakan', 'Export untuk laporan compliance'],
    faqs: [
      { question: 'Berapa lama log disimpan?', answer: 'Log disimpan permanen. Bisa di-archive per periode.' },
      { question: 'Siapa yang bisa akses?', answer: 'Hanya Owner, Super Admin, dan HQ Admin.' },
    ],
    relatedModules: ['settings'],
    userRoles: [{ role: 'Owner/Admin', access: 'Full audit access' }],
    lastUpdated: '2026-03-01', readTime: '4 menit', difficulty: 'beginner',
  },

  // ── SYSTEM ──
  {
    slug: 'pengaturan-sistem',
    title: 'Pengaturan Sistem',
    subtitle: 'Konfigurasi global, pajak, notifikasi',
    category: 'system', module: 'settings', icon: 'Settings', color: 'slate', gradient: 'from-slate-500 to-slate-600',
    overview: 'Konfigurasi global sistem: pengaturan toko, pajak, metode pembayaran, notifikasi, integrasi pihak ketiga, dan preferensi akun.',
    keyFeatures: ['Global settings', 'Pajak & biaya', 'Metode pembayaran', 'Notifikasi', 'Integrasi', 'Backup & security'],
    businessFlow: {
      title: 'Alur Konfigurasi', description: 'Setup awal dan ongoing',
      steps: [
        { id: 1, label: 'Initial', description: 'Setup setelah aktivasi', actor: 'Owner', action: 'Configure basics' },
        { id: 2, label: 'Tax', description: 'Atur pajak & fee', actor: 'Owner', action: 'Set tax rates' },
        { id: 3, label: 'Payment', description: 'Atur metode bayar', actor: 'Owner', action: 'Enable gateways' },
        { id: 4, label: 'Notif', description: 'Atur notifikasi', actor: 'Owner', action: 'Set preferences' },
        { id: 5, label: 'Integrate', description: 'Connect 3rd party', actor: 'Admin', action: 'API setup' },
      ],
    },
    sequenceDiagram: [
      { from: 'Owner', to: 'Settings', action: 'Update', description: 'Ubah konfigurasi', type: 'request' },
      { from: 'Settings', to: 'System', action: 'Apply', description: 'Terapkan ke semua cabang', type: 'action' },
      { from: 'System', to: 'Owner', action: 'Confirm', description: 'Settings tersimpan', type: 'response' },
    ],
    usageGuide: [
      { step: 1, title: 'Global Settings', description: 'Info toko, mata uang, timezone.' },
      { step: 2, title: 'Pajak', description: 'Set PPN, service charge, dll.' },
      { step: 3, title: 'Pembayaran', description: 'Aktifkan metode: QRIS, e-wallet, kartu.' },
      { step: 4, title: 'Notifikasi', description: 'Atur alert email, push, WA.' },
      { step: 5, title: 'Integrasi', description: 'Connect accounting software, payment gateway.' },
    ],
    tips: ['Konfigurasi pajak di awal', 'Test payment gateway sebelum live', 'Backup settings berkala'],
    faqs: [
      { question: 'Setting berlaku global?', answer: 'Ya, tapi bisa di-override per cabang.' },
      { question: 'Bisa integrasi accounting software?', answer: 'Ya, via API atau file export.' },
    ],
    relatedModules: ['dashboard'],
    userRoles: [{ role: 'Owner/Admin', access: 'Full config' }],
    lastUpdated: '2026-03-01', readTime: '5 menit', difficulty: 'beginner',
  },
];

// Quick search helper
export function searchArticles(query: string): KBArticle[] {
  const q = query.toLowerCase();
  return KB_ARTICLES.filter(a =>
    a.title.toLowerCase().includes(q) ||
    a.subtitle.toLowerCase().includes(q) ||
    a.overview.toLowerCase().includes(q) ||
    a.keyFeatures.some(f => f.toLowerCase().includes(q)) ||
    a.faqs.some(f => f.question.toLowerCase().includes(q) || f.answer.toLowerCase().includes(q))
  );
}

export function getArticleBySlug(slug: string): KBArticle | undefined {
  return KB_ARTICLES.find(a => a.slug === slug);
}

export function getArticlesByCategory(category: KBCategory): KBArticle[] {
  return KB_ARTICLES.filter(a => a.category === category);
}
